#!/usr/bin/env ruby
require 'fileutils.rb'

pkg_path = File.expand_path($0).split('/')
pkg_path = pkg_path[0,pkg_path.length-1].join('/')
puts "package path: [#{pkg_path}]"
if pkg_path.length < 1
  puts "woah! package path looks scary. something isn't right. bailing..."
  exit
end

Dir.chdir(pkg_path)
# TODO make sure we got there

if ARGV.length == 0 || ARGV[0] == 'update'
  puts "extracting ffmpeg ============================"
  system("tar xjvf ffmpeg-export-snapshot.tar.bz2")
  puts "configuring ffmpeg ============================"
  Dir.chdir "#{pkg_path}/ffmpeg-export-2008-03-18"
  system("./configure --enable-shared --prefix=${PWD}/..")
# TODO check for blowups after configure
  puts "making opencv ================================="
  system("make")
  puts "moving files around ============================"
  system("make install")
  Dir.chdir pkg_path
  Dir.mkdir "include/ffmpeg"
  system "ln -s include/libavcodec/avcodec.h include/ffmpeg/avcodec.h"
  system "ln -s include/libavformat/avformat.h include/ffmpeg/avformat.h"
# TODO check for make errors
  puts "done! hooray! =================================="
elsif ARGV[0] == 'clean'
  Dir.chdir "#{pkg_path}"
  system("rm -rf bin")
  system("rm -rf include")
  system("rm -rf lib")
  system("rm -rf ffmpeg-export-2008-03-18")
  puts "done!"
else
  puts "unknown parameter: #{ARGV[0]}"
end

