import os

opts = Options()
opts.Add('prefix', 'The install path "prefix"', '/usr/local')
opts.Add('destdir', 'The root directory to install into. Useful mainly for binary package building', '/')

env = Environment (
  CC = 'g++',
  CCFLAGS = Split ('-pthread -pipe  -W -Wall -O2'),
  options=opts
)

ROOT = os.environ['SIM_TOP']+'/root'
BINROOT = ROOT + '/bin'
LIBROOT = ROOT + '/lib'
INCROOT = ROOT + '/include'


Help(opts.GenerateHelpText(env))

if env['destdir'] != '/':
  install_prefix = env['destdir'] + '/' + env['prefix']
else:
  install_prefix = env['prefix']

# 3rd party packages
parseConfigs=['pkg-config --cflags --libs libgazebo',
              'xml2-config --cflags --libs',
              'pkg-config --cflags --libs playerc++',	
              'pkg-config --cflags --libs libgazeboServer']

# Parse all the package configurations
for cfg in parseConfigs:
  env.ParseConfig(cfg)

# install headers.
headers = Split('PR2.hh');

actarray_sharedLib = env.SharedLibrary('Pr2_Actarray','Pr2_Actarray.cc');
gripper_sharedLib  = env.SharedLibrary('Pr2_Gripper' ,'Pr2_Gripper.cc' );
P3D_sharedLib  = env.SharedLibrary('P3D' ,'P3D.cc' );

env.Program('pr2','pr2.cc');

env.Install(LIBROOT, [actarray_sharedLib,gripper_sharedLib,P3D_sharedLib]);
env.Install(INCROOT,headers);


env.Alias('install',[LIBROOT,INCROOT])


