#!/bin/bash


rm -r testcameraframes/
./run-gazebo.sh world/testcameras.world

diff -q test/testcamera.valid.jpg testcameraframes/genericCam-0050.jpg 

if [ $? = 0 ]; then
   exit 0
else
   exit 1
fi

