string channel_name                         # User defined name
time start                                  # The start time of the resulting interval
time end                                    # The end time of the resulting interval
calibration_msgs/ImagePointStamped pixel    # The settled pixel location
sensor_msgs/Image image                     # The image used to calculate the pixel location
