SRC = map_server.cc
OUT = map_server
PKG = map_server
CFLAGS = -Wall -Werror `pkg-config --cflags gdk-pixbuf-2.0`
LFLAGS = `pkg-config --libs gdk-pixbuf-2.0`
include $(shell rospack find mk)/node.mk

