#!/usr/bin/env ruby
require "#{`#{ENV['ROS_ROOT']}/rospack latest yamlgraph`}/lib/yamlgraph/ygl.rb"
g = YAMLGraph.new
g.param 'elphel_cam.host', '192.168.0.9'
g.param 'elphel_cam.fps', '80'
g.param 'elphel_cam.im_dec', '4'
g.node 'elphel_cam/elphel_cam', {'launch'=>'xterm'}
g.node 'simple_sdl_gui/gui', {'launch'=>'xterm'}
#g.node 'vacuum/vacuum', {'launch' => 'valgrind'}
g.flow 'elphel_cam:image', 'gui:image'
#g.flow 'elphel_cam:image', 'vacuum:hose'
YAMLGraphLauncher.new.launch g

