#!/usr/bin/env ruby
(puts "aaaaaaaa no ROS_ROOT"; exit) if !ENV['ROS_ROOT']
require "#{`#{ENV['ROS_ROOT']}/rospack latest yamlgraph`}/lib/yamlgraph/yamlgraph_launcher.rb"
g = ROS_Graph.new
g.param 'servo.host', '192.168.1.38'
g.node  'ipdcmot/servo'
g.node  'ipdcmot/servo_stepper'
g.flow  'servo_stepper.getpos_request', 'servo.getpos_blocking'
g.flow  'servo.getpos_result', 'servo_stepper.getpos_result'
g.flow  'servo_stepper.setpos_request', 'servo.setpos_blocking'
g.flow  'servo.setpos_result', 'servo_stepper.setpos_result'
ROS_GraphLauncher.new.launch g

