SUBDIRS = test_comms calibrate motor_power goto_upright get_joint_solution linear_move log_encoders move_gripper move_joint_deg move_robot_deg move_sequence print_arm_state print_encoders
include $(shell rospack find mk)/recurse_subdirs.mk

