#!/usr/bin/env ruby
require "#{`#{ENV['ROS_ROOT']}/rospack latest yamlgraph`}/lib/yamlgraph/ygl.rb"
g = YAMLGraph.new
g.param 'axis_cam.host', '192.168.1.90'
g.node 'axis_cam/axis_cam', {'launch'=>'xterm'}
g.node 'image_viewer/image_viewer', {'launch'=>'xterm'}
g.node 'image_viewer/image_viewer', {'name'=>'iv2','launch'=>'xterm'}
g.flow 'axis_cam:image', 'image_viewer:image'
g.flow 'axis_cam:image', 'iv2:image'
YAMLGraphLauncher.new.launch g

