#SUBDIRS = libetherdrive etherdrive_node etherdrive_node_controller encoder_monitor caster_node base_node caster_keyboard
#SUBDIRS = libetherdrive etherdrive_node etherdrive_node_controller base_node etherdrivehardware
SUBDIRS = libetherdrive
include $(shell rospack find mk)/recurse_subdirs.mk
