#!/usr/bin/env ruby
require "#{`#{ENV['ROS_ROOT']}/rospack latest yamlgraph`}/lib/yamlgraph/ygl.rb"
g = YAMLGraph.new
g.node 'tilting_laser/tilting_laser', {'launch'=>'xterm'}
g.param 'hokuyourg.port', '/dev/ttyACM0'
g.node 'hokuyourg_player/hokuyourg', {'launch'=>'xterm'}
g.node 'etherdrive/etherdrive', {'launch'=>'xterm'}
g.param 'etherdrive.pulse_per_rad1', '9549.29659'
g.node 'cloud_viewer/cloud_node', {'launch'=>'xterm'}
g.flow 'etherdrive:mot1', 'tilting_laser:encoder'
g.flow 'tilting_laser:cmd', 'etherdrive:mot1_cmd'
g.param 'tilting_laser.period', '10.0'
g.flow 'hokuyourg:scans', 'tilting_laser:scans'
g.flow 'tilting_laser:cloud', 'cloud_node:cloud'
g.flow 'tilting_laser:shutter', 'cloud_node:shutter'
YAMLGraphLauncher.new.launch g

