SRC = src/Controller.cpp src/BaseController.cpp src/HeadController.cpp src/SpineController.cpp src/ArmController.cpp src/LaserScannerController.cpp src/JointController.cpp src/GripperController.cpp
OUT = lib/libPr2Controllers.a
PKG = pr2Controllers
include $(shell rospack find mk)/lib.mk

