#SRC = src/BaseController.cpp src/HeadController.cpp src/SpineController.cpp src/ArmController.cpp src/LaserScannerController.cpp src/GripperController.cpp
SRC = src/BaseController.cpp
OUT = lib/libpr2Controllers.a
PKG = pr2Controllers
include $(shell rospack find mk)/lib.mk

