#!/usr/bin/env ruby
(puts "aaaaaaaa no ROS_ROOT"; exit) if !ENV['ROS_ROOT']
rosrb = `#{ENV['ROS_ROOT']}/rospack latest rosrb`
require "#{rosrb}/lib/rosrb/launcher"
l = Launcher.new('camera_calibration','bin/calibrator',['cpp','xterm','persist'])
Kernel.exec(l.cmd, *l.args)
