# A request to the topological planner for a cost estimate of all connectors
# between two 2d poses

std_msgs/Pose2DFloat32 start
std_msgs/Pose2DFloat32 goal

---

std_msgs/Pose2DFloat32[] connectors
float64[] costs
