# Service implemented by 2d navigation planners
deprecated_msgs/Pose2DFloat32 start
deprecated_msgs/Pose2DFloat32 goal

---
# Response is an array of waypoints, where the first one is the start and the last is the goal
deprecated_msgs/Pose2DFloat32[] waypoints

