# this service wraps the transformPose method in TransformListener (both versions).
# if fixed_frame is empty the non-interpolating version is called and time is ignored.

string target_frame
time   target_time 
robot_msgs/PoseStamped pin
string fixed_frame
---
robot_msgs/PoseStamped pout