#ifndef __FOREARM_CAM__MT9V_H__
#define __FOREARM_CAM__MT9V_H__

#define MT9V_REG_WINDOW_WIDTH 0x04
#define MT9V_REG_HORIZONTAL_BLANKING 0x05
#define MT9V_REG_VERTICAL_BLANKING 0x06
#define MT9V_REG_TOTAL_SHUTTER_WIDTH 0x0B
#define MT9V_REG_ANALOG_GAIN 0x35
#define MT9V_REG_AGC_AEC_ENABLE 0xAF

#define MT9V_CK_FREQ 16e6

#endif
