/* auto-generated by genmsg_cpp from /u/ethand/ros/ros-pkg/sandbox/follower/msg/MoveHeadGoal.msg.  Do not edit! */
#ifndef FOLLOWER_MOVEHEADGOAL_H
#define FOLLOWER_MOVEHEADGOAL_H

#include <string>
#include <vector>
#include "ros/message.h"
#include "ros/time.h"

namespace follower
{

//! \htmlinclude MoveHeadGoal.msg.html

class MoveHeadGoal : public ros::Message
{
public:
  typedef boost::shared_ptr<MoveHeadGoal> Ptr;
  typedef boost::shared_ptr<MoveHeadGoal const> ConstPtr;


  MoveHeadGoal() : ros::Message()
  {
  }
  MoveHeadGoal(const MoveHeadGoal &copy) : ros::Message()
  {
    (void)copy;
  }
  MoveHeadGoal &operator =(const MoveHeadGoal &copy)
  {
    if (this == &copy)
      return *this;
    return *this;
  }
  virtual ~MoveHeadGoal() 
  {
  }
  inline static std::string __s_getDataType() { return std::string("follower/MoveHeadGoal"); }
  inline static std::string __s_getMD5Sum() { return std::string("d41d8cd98f00b204e9800998ecf8427e"); }
  inline static std::string __s_getMessageDefinition()
  {
    return std::string(
    "\n"
    "\n"
    "\n"
    );
  }
  inline virtual const std::string __getDataType() const { return __s_getDataType(); }
  inline virtual const std::string __getMD5Sum() const { return __s_getMD5Sum(); }
  inline virtual const std::string __getMessageDefinition() const { return __s_getMessageDefinition(); }
  inline uint32_t serializationLength() const
  {
    unsigned __l = 0;
    return __l;
  }
  virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    return write_ptr;
  }
  virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    return read_ptr;
  }
};

typedef boost::shared_ptr<MoveHeadGoal> MoveHeadGoalPtr;
typedef boost::shared_ptr<MoveHeadGoal const> MoveHeadGoalConstPtr;


}

#endif
