#!/bin/bash

cd $(dirname $0)
mv Makefile Makefile.ros
$HOME/cmake-2.6.4/bin/cmake -G"Eclipse CDT4 - Unix Makefiles" -Wno-dev .
rm Makefile
rm CMakeCache.txt
rm -rf CMakeFiles
mv Makefile.ros Makefile

