#!/bin/bash
#This file is needed, to force the use of bash, so devConfig can be sourced.

if [ `uname` = Darwin ]; then
  export DYLD_BIND_AT_LAUNCH=YES
fi

#Have to be here to source it.
cd `rospack find trex`

# PLASMA_HOME is required to build the PLASMA NDDL.jar
source `rospack find trex`/TREX/devConfig

cd `rospack find trex`/TREX

echo "Building nddl.jar with jam"
# Build the nddl jar file used to parse input files
jam  -q nddl.jar

if [ $? -ne 0 ] ; then
    echo "Jam of nddl.jar failed."
    exit 1
fi


# Build function takes:
# 1. library name
# 2. jam flags
# 3. return error code
function run_jam {
  echo "Running jam with command" $1 " and options" $2
  if [ `uname` = Darwin ]; then
    jam $2  -q $1.dylib
  else
    jam $2  -q $1.so
  fi
  if [ $? -ne 0 ] ; then
    echo "Jam of $1 failed."
    exit $3
  fi
}


if [ "$1" = "test" ] ; then
  cd `rospack find trex`/TREX/agent/test
  jam agent-module-tests
  if [ $? -ne 0 ] ; then
    echo "Test file creation failed."
    exit 1
  fi
  jam run-agent-module-tests
  if [ $? -ne 0 ] ; then
    echo "Tests failed."
    exit 1
  fi

else
  if [ "$ROS_TREX_DEBUG" = "1" ] ; then
      run_jam "libTREX_g" " " 1
  fi
  run_jam "libTREX_o" "-sVARIANTS=OPTIMIZED -sLIBRARIES=SHARED" 2
fi

cd ../

