all: xenomai_kernel xenomai_user
	@echo "No tests for xenomai installation implemented yet, so I'm trusting you"

xenomai_kernel:
	@echo "Make sure you have xenomai support compiled into your kernel"

xenomai_user:
	@echo "Make sure you have xenomai user-space support at /usr/xenomai with a configuration that matches your kernel"
