include $(shell rospack find mk)/cmake.mk

#CFLAGS=-fPIC -ggdb -Wall 
#CCFLAGS=-fPIC -ggdb -Wall 
#CPPFLAGS=-fPIC -ggdb -Wall 
#LIBS=#-lreadline

#all: power

#power: power.o power_comm.h	
#	g++ $(CCFLAGS) $(LINKINCLUDES) $(LIBS) -o $@ $^ 

#clean:
#	rm *.o power