#!/usr/bin/env ruby
(puts "aaaaaa no ROS_ROOT"; exit) if !ENV['ROS_ROOT']
require "#{`#{ENV['ROS_ROOT']}/rospack latest yamlgraph`}/lib/yamlgraph/ygl.rb"
g = YAMLGraph.new
g.param 'range_sender.freq', '1000.0'

g.param 'ros_launch_args', ["/usr/bin/xterm", "-T", "%(node_name)s", "-e", "bash", "-c", "valgrind %(rospack)s run %(pkg)s %(node_type)s; bash"]

g.node 'range_flows/range_sender'
g.node 'range_flows/range_receiver'
g.flow 'range_sender.scan', 'range_receiver.scan'
YAMLGraphLauncher.new.launch g
