// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "stereogui.h"

Fl_Menu_Item stereogui::menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 56},
 {"Load Images...", 0,  (Fl_Callback*)load_images_cb, 0, 128, FL_NORMAL_LABEL, 0, 14, 56},
 {"Save Images...", 0,  (Fl_Callback*)save_images_cb, 0, 128, FL_NORMAL_LABEL, 0, 14, 56},
 {"Load Params...", 0,  (Fl_Callback*)load_params_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 56},
 {"Save Params...", 0,  (Fl_Callback*)save_params_cb, 0, 128, FL_NORMAL_LABEL, 0, 14, 56},
 {"Exit", 0,  (Fl_Callback*)do_exit_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 56},
 {0,0,0,0,0,0,0,0,0},
 {"Video...", 0,  (Fl_Callback*)video_window_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 56},
 {"Stereo...", 0,  (Fl_Callback*)stereo_window_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 56},
 {"Calibrate...", 0,  (Fl_Callback*)cal_window_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 56},
 {"Debug...", 0,  (Fl_Callback*)debug_window_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 56},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item stereogui::menu_Stereo[] = {
 {"Normal", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 56},
 {"Scanline Opt", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 56},
 {"DP", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 56},
 {"Multiple Windows", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 56},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item stereogui::menu_Size[] = {
 {"320x240", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 56},
 {"640x480", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 56},
 {"1280x960", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 56},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item stereogui::menu_Rate[] = {
 {"30 Hz", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 56},
 {"15 Hz", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 56},
 {"7.5 Hz", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 56},
 {0,0,0,0,0,0,0,0,0}
};

stereogui::stereogui() {
  Fl_Window* w;
  { Fl_Window* o = ost_main = new Fl_Window(655, 305, "Open STereo");
    w = o;
    o->labelsize(11);
    o->user_data((void*)(this));
    { Fl_Output* o = info_message = new Fl_Output(5, 275, 490, 25);
      o->box(FL_BORDER_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->labelsize(11);
      o->textsize(11);
    }
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 680, 20);
      o->menu(menu_);
    }
    { Fl_Group* o = new Fl_Group(5, 25, 645, 245);
      { Fl_Group* o = new Fl_Group(5, 25, 320, 245);
        { Fl_Box* o = new Fl_Box(5, 25, 320, 240);
          o->box(FL_EMBOSSED_FRAME);
          o->labeltype(FL_NO_LABEL);
        }
        { calImageWindow* o = mainLeft = new calImageWindow(5, 25, 320, 240);
          o->box(FL_NO_BOX);
          o->color(FL_BACKGROUND_COLOR);
          o->selection_color(FL_BACKGROUND_COLOR);
          o->labeltype(FL_NO_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_BLACK);
          o->align(FL_ALIGN_CENTER);
          o->when(FL_WHEN_RELEASE);
        }
        o->end();
      }
      { Fl_Group* o = new Fl_Group(330, 25, 320, 245);
        { Fl_Box* o = new Fl_Box(330, 25, 320, 240);
          o->box(FL_EMBOSSED_FRAME);
          o->labeltype(FL_NO_LABEL);
        }
        { calImageWindow* o = mainRight = new calImageWindow(330, 25, 320, 240);
          o->box(FL_NO_BOX);
          o->color(FL_BACKGROUND_COLOR);
          o->selection_color(FL_BACKGROUND_COLOR);
          o->labeltype(FL_NO_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_BLACK);
          o->align(FL_ALIGN_CENTER);
          o->when(FL_WHEN_RELEASE);
        }
        o->end();
      }
      o->end();
    }
    o->end();
  }
  { Fl_Window* o = cal_images = new Fl_Window(675, 295, "Calibration images");
    w = o;
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(5, 0, 855, 375);
      { Fl_Tabs* o = window_tab = new Fl_Tabs(5, 0, 665, 295);
        o->box(FL_UP_BOX);
        o->labeltype(FL_NO_LABEL);
        { Fl_Group* o = tab1 = new Fl_Group(10, 35, 660, 250, " 1 ");
          o->labelsize(11);
          o->user_data((void*)(1));
          o->hide();
          o->deactivate();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 35, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft1 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(340, 35, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight1 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab2 = new Fl_Group(10, 25, 660, 260, " 2");
          o->labelsize(11);
          o->user_data((void*)(2));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft2 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight2 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab3 = new Fl_Group(10, 25, 660, 260, " 3");
          o->labelsize(11);
          o->user_data((void*)(3));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft3 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight3 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab4 = new Fl_Group(10, 25, 660, 260, " 4");
          o->labelsize(11);
          o->user_data((void*)(4));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft4 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight4 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab5 = new Fl_Group(10, 25, 660, 260, " 5");
          o->labelsize(11);
          o->user_data((void*)(5));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft5 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight5 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab6 = new Fl_Group(10, 25, 660, 260, " 6");
          o->labelsize(11);
          o->user_data((void*)(6));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft6 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight6 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab7 = new Fl_Group(10, 25, 660, 260, " 7");
          o->labelsize(11);
          o->user_data((void*)(7));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft7 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight7 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab8 = new Fl_Group(10, 25, 660, 260, " 8");
          o->labelsize(11);
          o->user_data((void*)(8));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft8 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight8 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab9 = new Fl_Group(10, 25, 660, 260, " 9");
          o->labelsize(11);
          o->user_data((void*)(9));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft9 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight9 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab10 = new Fl_Group(10, 25, 660, 260, " 10");
          o->labelsize(11);
          o->user_data((void*)(10));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft10 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight10 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab11 = new Fl_Group(10, 25, 660, 260, " 11");
          o->labelsize(11);
          o->user_data((void*)(11));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft11 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight11 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab12 = new Fl_Group(10, 25, 660, 260, " 12");
          o->labelsize(11);
          o->user_data((void*)(12));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft12 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight12 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab13 = new Fl_Group(10, 25, 660, 260, " 13");
          o->labelsize(11);
          o->user_data((void*)(13));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft13 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight13 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab14 = new Fl_Group(10, 25, 660, 260, " 14");
          o->labelsize(11);
          o->user_data((void*)(14));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft14 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight14 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab15 = new Fl_Group(10, 25, 660, 260, " 15");
          o->labelsize(11);
          o->user_data((void*)(15));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft15 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight15 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab16 = new Fl_Group(10, 25, 660, 260, " 16");
          o->labelsize(11);
          o->user_data((void*)(16));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft16 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight16 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab17 = new Fl_Group(10, 25, 660, 260, " 17");
          o->labelsize(11);
          o->user_data((void*)(17));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft17 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight17 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab18 = new Fl_Group(10, 25, 660, 260, " 18");
          o->labelsize(11);
          o->user_data((void*)(18));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft18 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight18 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab19 = new Fl_Group(10, 25, 660, 260, " 19");
          o->labelsize(11);
          o->user_data((void*)(19));
          o->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft19 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight19 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        { Fl_Group* o = tab20 = new Fl_Group(10, 25, 660, 260, " 20");
          o->labelsize(11);
          o->user_data((void*)(20));
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calLeft20 = new calImageWindow(15, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              }
              { calImageWindow* o = calRight20 = new calImageWindow(340, 35, 320, 240);
                o->box(FL_NO_BOX);
                o->color(FL_BACKGROUND_COLOR);
                o->selection_color(FL_BACKGROUND_COLOR);
                o->labeltype(FL_NO_LABEL);
                o->labelfont(0);
                o->labelsize(14);
                o->labelcolor(FL_BLACK);
                o->align(FL_ALIGN_CENTER);
                o->when(FL_WHEN_RELEASE);
              }
              o->end();
            }
            o->end();
          }
          o->end();
        }
        o->end();
      }
      o->end();
    }
    o->end();
  }
  { Fl_Window* o = cal_window = new Fl_Window(305, 340, "Calibration");
    w = o;
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(10, 20, 160, 300);
      { Fl_Button* o = capture_button = new Fl_Button(10, 20, 90, 25, "Capture");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_capture_cb);
        o->user_data((void *)this);
      }
      { Fl_Button* o = load_button = new Fl_Button(10, 130, 90, 25, "Load both");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_load_cb);
        o->user_data((void *)this);
      }
      { Fl_Button* o = save_button = new Fl_Button(10, 200, 90, 25, "Save");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_save_image_cb);
        o->user_data((void *)this);
      }
      { Fl_Button* o = save_all_button = new Fl_Button(10, 225, 90, 25, "Save All");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_save_all_cb);
        o->user_data((void *)this);
      }
      { Fl_Button* o = delete_button = new Fl_Button(10, 265, 90, 25, "Delete");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_delete_image);
        o->user_data((void *)this);
      }
      { Fl_Button* o = load_left_button = new Fl_Button(10, 105, 45, 25, "Load L");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_load_left_cb);
        o->user_data((void *)this);
      }
      { Fl_Button* o = load_right_button = new Fl_Button(55, 105, 45, 25, "Load R");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_load_right_cb);
        o->user_data((void *)this);
      }
      { Fl_Button* o = load_seq_button = new Fl_Button(10, 155, 90, 25, "Load sequence");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_load_seq_cb);
        o->user_data((void *)this);
      }
      { Fl_Light_Button* o = track_button = new Fl_Light_Button(10, 55, 100, 25, "Track chessboard");
        o->labelsize(11);
        o->callback((Fl_Callback*)do_track_cb);
        Fl_Group::current()->resizable(o);
      }
      o->end();
    }
    { Fl_Group* o = new Fl_Group(130, 200, 175, 55);
      { Fl_Box* o = new Fl_Box(130, 200, 150, 50, "label");
        o->box(FL_ENGRAVED_FRAME);
        o->labeltype(FL_NO_LABEL);
      }
      { Fl_Value_Input* o = user_check_size = new Fl_Value_Input(145, 220, 30, 20, "Size mm");
        o->labelsize(11);
        o->maximum(1000);
        o->step(1);
        o->value(100);
        o->textsize(11);
        o->callback((Fl_Callback*)cal_check_size_cb);
        o->align(FL_ALIGN_TOP);
      }
      { Fl_Value_Input* o = user_check_x = new Fl_Value_Input(190, 220, 30, 20, "Ints X");
        o->labelsize(11);
        o->maximum(100);
        o->step(1);
        o->value(8);
        o->textsize(11);
        o->callback((Fl_Callback*)cal_check_x_cb);
        o->align(FL_ALIGN_TOP);
      }
      { Fl_Value_Input* o = user_check_y = new Fl_Value_Input(230, 220, 30, 20, "Ints Y");
        o->labelsize(11);
        o->maximum(100);
        o->step(1);
        o->value(6);
        o->textsize(11);
        o->callback((Fl_Callback*)cal_check_y_cb);
        o->align(FL_ALIGN_TOP);
      }
      o->end();
    }
    { Fl_Group* o = new Fl_Group(120, 20, 165, 290);
      { Fl_Button* o = calibrate_button = new Fl_Button(135, 20, 75, 25, "Calibrate");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_calibrate_cb);
        o->user_data((void *)this);
      }
      { Fl_Button* o = save_params_button = new Fl_Button(220, 20, 65, 25, "Save params");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_save_params_cb);
        o->user_data((void *)this);
      }
      { Fl_Button* o = done_button = new Fl_Button(135, 50, 60, 25, "Done");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_ok_cb);
        o->user_data((void *)this);
      }
      { Fl_Button* o = epi_button = new Fl_Button(220, 50, 60, 25, "Epi check");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_epipolar_cb);
        o->user_data((void *)this);
      }
      { Fl_Button* o = upload_params_button = new Fl_Button(130, 270, 130, 40, "Upload params");
        o->down_box(FL_DOWN_BOX);
        o->callback((Fl_Callback*)cal_upload_params_cb);
        o->user_data((void *)this);
      }
      o->end();
    }
    { Fl_Group* o = new Fl_Group(125, 105, 180, 95);
      { Fl_Box* o = new Fl_Box(130, 105, 170, 85);
        o->box(FL_ENGRAVED_FRAME);
      }
      { Fl_Check_Button* o = fixed_aspect_button = new Fl_Check_Button(210, 130, 85, 25, "Fixed Aspect");
        o->down_box(FL_DOWN_BOX);
        o->value(1);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_fixed_aspect_cb);
      }
      { Fl_Check_Button* o = fixed_kappa2_button = new Fl_Check_Button(135, 110, 25, 25, "Kappa2");
        o->down_box(FL_DOWN_BOX);
        o->value(1);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_fixed_kappa2_cb);
      }
      { Fl_Check_Button* o = fixed_kappa3_button = new Fl_Check_Button(135, 130, 25, 25, "Kappa3");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_fixed_kappa3_cb);
      }
      { Fl_Check_Button* o = fixed_tau_button = new Fl_Check_Button(135, 150, 25, 25, "Tau1, Tau2");
        o->down_box(FL_DOWN_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_fixed_tau_cb);
      }
      { Fl_Check_Button* o = zero_disparity_button = new Fl_Check_Button(210, 110, 85, 25, "Zero disparity");
        o->down_box(FL_DOWN_BOX);
        o->value(1);
        o->labelsize(11);
        o->callback((Fl_Callback*)cal_zero_disparity_cb);
      }
      o->end();
    }
    o->end();
  }
  { Fl_Window* o = stereo_window = new Fl_Window(340, 295, "Stereo");
    w = o;
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(15, 155, 285, 120);
      { Fl_Box* o = new Fl_Box(15, 155, 280, 110, "label");
        o->box(FL_ENGRAVED_FRAME);
        o->labeltype(FL_NO_LABEL);
      }
      { Fl_Counter* o = new Fl_Counter(85, 160, 55, 20, "UniqueThresh");
        o->type(1);
        o->labelsize(11);
        o->minimum(0);
        o->maximum(100);
        o->step(1);
        o->value(30);
        o->callback((Fl_Callback*)unique_cb);
        o->align(FL_ALIGN_LEFT);
      }
      { Fl_Counter* o = new Fl_Counter(85, 185, 55, 20, "TextureThresh");
        o->type(1);
        o->labelsize(11);
        o->minimum(0);
        o->maximum(100);
        o->step(1);
        o->value(30);
        o->callback((Fl_Callback*)texture_cb);
        o->align(FL_ALIGN_LEFT);
      }
      { Fl_Counter* o = new Fl_Counter(85, 210, 55, 20, "SpeckleSize");
        o->type(1);
        o->labelsize(11);
        o->minimum(0);
        o->maximum(400);
        o->step(10);
        o->value(100);
        o->callback((Fl_Callback*)speckle_size_cb);
        o->align(FL_ALIGN_LEFT);
      }
      { Fl_Counter* o = new Fl_Counter(85, 235, 55, 20, "SpeckleDiff");
        o->type(1);
        o->labelsize(11);
        o->minimum(0);
        o->maximum(20);
        o->step(1);
        o->value(8);
        o->callback((Fl_Callback*)speckle_diff_cb);
        o->align(FL_ALIGN_LEFT);
      }
      { Fl_Counter* o = new Fl_Counter(230, 160, 55, 20, "Smoothness");
        o->type(1);
        o->labelsize(11);
        o->minimum(0);
        o->maximum(100);
        o->step(1);
        o->value(30);
        o->callback((Fl_Callback*)smoothness_cb);
        o->align(FL_ALIGN_LEFT);
      }
      o->end();
    }
    { Fl_Group* o = new Fl_Group(20, 30, 320, 110);
      { Fl_Box* o = new Fl_Box(20, 30, 120, 85);
        o->box(FL_ENGRAVED_FRAME);
      }
      { Fl_Counter* o = new Fl_Counter(75, 35, 55, 20, "Disparity:");
        o->type(1);
        o->labelsize(11);
        o->minimum(16);
        o->maximum(128);
        o->step(16);
        o->value(64);
        o->callback((Fl_Callback*)disparity_cb);
        o->align(FL_ALIGN_LEFT);
      }
      { Fl_Counter* o = new Fl_Counter(75, 60, 55, 20, "Window:");
        o->type(1);
        o->labelsize(11);
        o->minimum(7);
        o->maximum(21);
        o->step(1);
        o->value(15);
        o->callback((Fl_Callback*)corrsize_cb);
        o->align(FL_ALIGN_LEFT);
      }
      { Fl_Counter* o = new Fl_Counter(75, 85, 55, 20, "X off:");
        o->type(1);
        o->labelsize(11);
        o->minimum(-4);
        o->maximum(128);
        o->step(1);
        o->callback((Fl_Callback*)xoff_cb);
        o->align(FL_ALIGN_LEFT);
      }
      { Fl_Light_Button* o = rectify_button = new Fl_Light_Button(160, 35, 75, 25, "Do Rectify");
        o->box(FL_THIN_UP_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)do_rectify_cb);
        o->user_data((void *)this);
      }
      { Fl_Light_Button* o = stereo_button = new Fl_Light_Button(160, 65, 75, 25, "Do Stereo");
        o->box(FL_THIN_UP_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)do_stereo_cb);
        o->user_data((void *)this);
      }
      { Fl_Light_Button* o = x3d_button = new Fl_Light_Button(160, 95, 75, 25, "Do 3D");
        o->box(FL_THIN_UP_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)do_3d_cb);
        o->user_data((void *)this);
      }
      { Fl_Choice* o = new Fl_Choice(245, 70, 90, 20, "Stereo Algorithm");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)stereo_algorithm_cb);
        o->align(FL_ALIGN_TOP_LEFT);
        o->menu(menu_Stereo);
      }
      o->end();
    }
    o->end();
  }
  { Fl_Window* o = video_window = new Fl_Window(425, 205, "Video");
    w = o;
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(20, 85, 285, 170);
      { Fl_Box* o = new Fl_Box(20, 125, 135, 70, "label");
        o->box(FL_ENGRAVED_FRAME);
        o->labeltype(FL_NO_LABEL);
      }
      { Fl_Choice* o = new Fl_Choice(50, 135, 90, 20, "Size");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)video_size_cb);
        o->menu(menu_Size);
      }
      { Fl_Choice* o = new Fl_Choice(50, 165, 90, 20, "Rate");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)video_rate_cb);
        o->menu(menu_Rate);
      }
      o->end();
    }
    { Fl_Group* o = new Fl_Group(20, 25, 295, 170);
      { Fl_Box* o = new Fl_Box(20, 25, 200, 85);
        o->box(FL_ENGRAVED_FRAME);
        o->labelsize(11);
      }
      { Fl_Light_Button* o = video_button = new Fl_Light_Button(30, 70, 50, 25, "Video");
        o->labelsize(11);
        o->callback((Fl_Callback*)do_video_cb);
      }
      { Fl_Choice* o = cam_select = new Fl_Choice(60, 35, 145, 20, "Cam");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)video_dev_cb);
      }
      { Fl_Light_Button* o = color_button = new Fl_Light_Button(100, 70, 45, 25, "Color");
        o->labelsize(11);
        o->callback((Fl_Callback*)do_color_cb);
      }
      { Fl_Light_Button* o = stoc_button = new Fl_Light_Button(160, 70, 45, 25, "STOC");
        o->labelsize(11);
        o->callback((Fl_Callback*)do_stoc_cb);
      }
      o->end();
    }
    { Fl_Group* o = new Fl_Group(190, 40, 215, 185);
      { Fl_Slider* o = exposure_val = new Fl_Slider(265, 40, 20, 130, "Exposure");
        o->type(4);
        o->labelsize(11);
        o->minimum(100);
        o->maximum(0);
        o->step(1);
        o->value(100);
        o->callback((Fl_Callback*)do_exposure_cb);
        o->align(FL_ALIGN_TOP);
      }
      { Fl_Slider* o = gain_val = new Fl_Slider(320, 40, 20, 130, "Gain");
        o->type(4);
        o->labelsize(11);
        o->maximum(100);
        o->step(1);
        o->callback((Fl_Callback*)do_gain_cb);
        o->align(FL_ALIGN_TOP);
      }
      { Fl_Slider* o = brightness_val = new Fl_Slider(375, 40, 20, 130, "Bright");
        o->type(4);
        o->labelsize(11);
        o->maximum(100);
        o->step(1);
        o->callback((Fl_Callback*)do_brightness_cb);
        o->align(FL_ALIGN_TOP);
      }
      { Fl_Light_Button* o = exposure_auto_button = new Fl_Light_Button(255, 175, 40, 20, "Auto");
        o->value(1);
        o->labelsize(11);
        o->callback((Fl_Callback*)do_auto_exposure_cb);
      }
      { Fl_Light_Button* o = gain_auto_button = new Fl_Light_Button(310, 175, 40, 20, "Auto");
        o->value(1);
        o->labelsize(11);
        o->callback((Fl_Callback*)do_auto_gain_cb);
      }
      { Fl_Light_Button* o = brightness_auto_button = new Fl_Light_Button(365, 175, 40, 20, "Auto");
        o->value(1);
        o->labelsize(11);
        o->callback((Fl_Callback*)do_auto_brightness_cb);
      }
      { Fl_Light_Button* o = gamma_button = new Fl_Light_Button(190, 135, 55, 25, "Gamma");
        o->value(1);
        o->labelsize(11);
        o->callback((Fl_Callback*)do_gamma_cb);
      }
      o->end();
    }
    o->end();
  }
}
