#!/bin/bash

function usage() {
    echo
    echo "Usage : led_ctrl <iface> <off|on>"
    echo "  iface  : ethernet interface led driver is connected to"
    echo "  off|on : turn led driver off or on"
    echo 
    echo "Example : led_ctrl eth0 on"
}

function run() {
    CMD="$*"
    echo "${CMD}"
    $CMD
    RESULT=$?
    if [[ "$RESULT" != "0" ]]
    then 
	echo "Error running command : ${CMD}"
	exit 1
    fi
}

if [[ ! -x "./mailbox" ]] ; then
   echo "cannot locate/execute mailbox util"
   exit 1
fi

ECAT_IFACE="$1"
if [[ -z "$ECAT_IFACE" ]] ; then
    echo "Please provide networking interface"
    usage
    exit 1
fi

case $2 in 
off)
        run ./mailbox -i$ECAT_IFACE -a0 -l1 -w0
        ;;
on)
        run ./mailbox -i$ECAT_IFACE -a0 -l1 -w1
        ;;
*)
        echo "Please specify on or off as second argument"
        usage
        exit 1
        ;;
esac