SRC = spectacles.cpp \
      tinyxml-2.5.3/tinystr.cpp \
      tinyxml-2.5.3/tinyxml.cpp \
      tinyxml-2.5.3/tinyxmlparser.cpp \
      tinyxml-2.5.3/tinyxmlerror.cpp
OUT = ../lib/libspectacles.a 
PKG = spectacles
CFLAGS = -I../include -I../include/tinyxml-2.5.3
include $(shell rospack find mk)/lib.mk
