SRC = hokuyo_top_urg.cpp
OUT = ../../lib/libstair__hokuyo_top_urg.a
PKG = stair__hokuyo_top_urg
CFLAGS = -I../../include -I$(shell $(ROS_ROOT)/rospack find stair__serial_port)/include
include $(shell $(ROS_ROOT)/rospack find roscpp)/make_include/only_rules_lib.mk
