#!/usr/bin/env ruby
require "#{`#{ENV['ROS_ROOT']}/rospack latest yamlgraph`}/lib/yamlgraph/ygl.rb"
g = YAMLGraph.new
g.node 'roscpp_demo/talker', {'launch'=>'xterm'}
g.node 'vacuum/vacuum', {'launch'=>'xterm'}
g.flow 'talker:out', 'vacuum:talker_out'
YAMLGraphLauncher.new.launch g

