#!/bin/bash
`rospack find xmlparam`/xmlparam `rospack find tilting_laser`/params.xml
xterm -e `rospack find hokuyourg_player`/hokuyourg_player&
xterm -e `rospack find etherdrive`/bin/etherdrive&
export ROS_NAMESPACE=TL
xterm -e `rospack find tilting_laser`/bin/tilting_laser mot:=/mot2 mot_cmd:=/mot2_cmd scan:=/scan&
