SRC = loneshark.cpp
OUT = loneshark
#LFLAGS = -L../../lib -laxis_cam -lcurl -lipdcmot
LFLAGS = -lcurl
LIBDEPS = ../../lib/libsharks.a
PKG = sharks
include $(shell $(ROS_ROOT)/rospack find roscpp)/make_include/node.mk
