#!/usr/bin/python -i 
# Software License Agreement (BSD License)
#
# Copyright (c) 2008, Willow Garage, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of the Willow Garage nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

# Written by Timothy Hunter <tjhunter@willowgarage.com> 2008

import rostools
import copy

# Loads interface with the robot.
rostools.update_path('teleop_robot')
from teleop_robot import *

ri = RobotInterface()

### Initialisation ###

ace = ri.spawnFile('pr2_arm/calibration_elbow.xml')
ace.calibrate()
del ace


acua = ri.spawnFile('pr2_arm/calibration_upper_arm.xml')
acua.calibrate()
del acua

acsp = ri.spawnFile('pr2_arm/calibration_shoulder_pan.xml')
acsp.calibrate()
del acsp


acsl = ri.spawnFile('pr2_arm/calibration_shoulder_lift.xml')
acsl.calibrate()
del acsl

### Arm ready to use ###

### Creating record ###

data=ri.createRecord()

### Spawning Arm position controller ###

print 'spawning the controller...'
raw_input()

j=ri.spawnFile('pr2_arm/pos_arm.xml')




#m=[('elbow_right_joint',1,0.1)]

#m2=[('elbow_right_joint',0,0.1)]

#j=ri.spawnFile('pr2_arm/pos_shoulder_lift.xml')

#ac = ri.spawnFile('pr2_arm/autotuner.xml')






