// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "stereolrfgui.h"

stereolrfgui::stereolrfgui() {
  { stereo_lrf_calibration = new Fl_Window(1120, 400, "Stereo / LRF Calibration");
    stereo_lrf_calibration->labelsize(11);
    stereo_lrf_calibration->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(10, 10, 1215, 355);
      { window_tab = new Fl_Tabs(10, 10, 995, 285);
        window_tab->box(FL_UP_BOX);
        window_tab->labeltype(FL_NO_LABEL);
        { tab1 = new Fl_Group(15, 45, 990, 250, " 1 ");
          tab1->labelsize(11);
          tab1->user_data((void*)(0));
          { Fl_Group* o = new Fl_Group(20, 45, 985, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft1 = new calImageWindow(20, 45, 320, 240);
                calLeft1->box(FL_NO_BOX);
                calLeft1->color(FL_BACKGROUND_COLOR);
                calLeft1->selection_color(FL_BACKGROUND_COLOR);
                calLeft1->labeltype(FL_NO_LABEL);
                calLeft1->labelfont(0);
                calLeft1->labelsize(14);
                calLeft1->labelcolor(FL_FOREGROUND_COLOR);
                calLeft1->align(FL_ALIGN_CENTER);
                calLeft1->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft1
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(345, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight1 = new calImageWindow(345, 45, 320, 240);
                calRight1->box(FL_NO_BOX);
                calRight1->color(FL_BACKGROUND_COLOR);
                calRight1->selection_color(FL_BACKGROUND_COLOR);
                calRight1->labeltype(FL_NO_LABEL);
                calRight1->labelfont(0);
                calRight1->labelsize(14);
                calRight1->labelcolor(FL_FOREGROUND_COLOR);
                calRight1->align(FL_ALIGN_CENTER);
                calRight1->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight1
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf1 = new calImageWindow(675, 45, 320, 240);
                calLrf1->box(FL_NO_BOX);
                calLrf1->color(FL_BACKGROUND_COLOR);
                calLrf1->selection_color(FL_BACKGROUND_COLOR);
                calLrf1->labeltype(FL_NO_LABEL);
                calLrf1->labelfont(0);
                calLrf1->labelsize(14);
                calLrf1->labelcolor(FL_FOREGROUND_COLOR);
                calLrf1->align(FL_ALIGN_CENTER);
                calLrf1->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf1
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab1->end();
        } // Fl_Group* tab1
        { tab2 = new Fl_Group(15, 45, 990, 250, " 2");
          tab2->labelsize(11);
          tab2->user_data((void*)(1));
          tab2->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft2 = new calImageWindow(20, 45, 320, 240);
                calLeft2->box(FL_NO_BOX);
                calLeft2->color(FL_BACKGROUND_COLOR);
                calLeft2->selection_color(FL_BACKGROUND_COLOR);
                calLeft2->labeltype(FL_NO_LABEL);
                calLeft2->labelfont(0);
                calLeft2->labelsize(14);
                calLeft2->labelcolor(FL_FOREGROUND_COLOR);
                calLeft2->align(FL_ALIGN_CENTER);
                calLeft2->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft2
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight2 = new calImageWindow(345, 45, 320, 240);
                calRight2->box(FL_NO_BOX);
                calRight2->color(FL_BACKGROUND_COLOR);
                calRight2->selection_color(FL_BACKGROUND_COLOR);
                calRight2->labeltype(FL_NO_LABEL);
                calRight2->labelfont(0);
                calRight2->labelsize(14);
                calRight2->labelcolor(FL_FOREGROUND_COLOR);
                calRight2->align(FL_ALIGN_CENTER);
                calRight2->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight2
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf2 = new calImageWindow(675, 45, 320, 240);
                calLrf2->box(FL_NO_BOX);
                calLrf2->color(FL_BACKGROUND_COLOR);
                calLrf2->selection_color(FL_BACKGROUND_COLOR);
                calLrf2->labeltype(FL_NO_LABEL);
                calLrf2->labelfont(0);
                calLrf2->labelsize(14);
                calLrf2->labelcolor(FL_FOREGROUND_COLOR);
                calLrf2->align(FL_ALIGN_CENTER);
                calLrf2->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf2
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab2->end();
        } // Fl_Group* tab2
        { tab3 = new Fl_Group(15, 35, 980, 260, " 3");
          tab3->labelsize(11);
          tab3->user_data((void*)(2));
          tab3->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft3 = new calImageWindow(20, 45, 320, 240);
                calLeft3->box(FL_NO_BOX);
                calLeft3->color(FL_BACKGROUND_COLOR);
                calLeft3->selection_color(FL_BACKGROUND_COLOR);
                calLeft3->labeltype(FL_NO_LABEL);
                calLeft3->labelfont(0);
                calLeft3->labelsize(14);
                calLeft3->labelcolor(FL_FOREGROUND_COLOR);
                calLeft3->align(FL_ALIGN_CENTER);
                calLeft3->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft3
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight3 = new calImageWindow(345, 45, 320, 240);
                calRight3->box(FL_NO_BOX);
                calRight3->color(FL_BACKGROUND_COLOR);
                calRight3->selection_color(FL_BACKGROUND_COLOR);
                calRight3->labeltype(FL_NO_LABEL);
                calRight3->labelfont(0);
                calRight3->labelsize(14);
                calRight3->labelcolor(FL_FOREGROUND_COLOR);
                calRight3->align(FL_ALIGN_CENTER);
                calRight3->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight3
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf3 = new calImageWindow(675, 45, 320, 240);
                calLrf3->box(FL_NO_BOX);
                calLrf3->color(FL_BACKGROUND_COLOR);
                calLrf3->selection_color(FL_BACKGROUND_COLOR);
                calLrf3->labeltype(FL_NO_LABEL);
                calLrf3->labelfont(0);
                calLrf3->labelsize(14);
                calLrf3->labelcolor(FL_FOREGROUND_COLOR);
                calLrf3->align(FL_ALIGN_CENTER);
                calLrf3->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf3
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab3->end();
        } // Fl_Group* tab3
        { tab4 = new Fl_Group(15, 35, 980, 260, " 4");
          tab4->labelsize(11);
          tab4->user_data((void*)(3));
          tab4->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft4 = new calImageWindow(20, 45, 320, 240);
                calLeft4->box(FL_NO_BOX);
                calLeft4->color(FL_BACKGROUND_COLOR);
                calLeft4->selection_color(FL_BACKGROUND_COLOR);
                calLeft4->labeltype(FL_NO_LABEL);
                calLeft4->labelfont(0);
                calLeft4->labelsize(14);
                calLeft4->labelcolor(FL_FOREGROUND_COLOR);
                calLeft4->align(FL_ALIGN_CENTER);
                calLeft4->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft4
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight4 = new calImageWindow(345, 45, 320, 240);
                calRight4->box(FL_NO_BOX);
                calRight4->color(FL_BACKGROUND_COLOR);
                calRight4->selection_color(FL_BACKGROUND_COLOR);
                calRight4->labeltype(FL_NO_LABEL);
                calRight4->labelfont(0);
                calRight4->labelsize(14);
                calRight4->labelcolor(FL_FOREGROUND_COLOR);
                calRight4->align(FL_ALIGN_CENTER);
                calRight4->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight4
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf4 = new calImageWindow(675, 45, 320, 240);
                calLrf4->box(FL_NO_BOX);
                calLrf4->color(FL_BACKGROUND_COLOR);
                calLrf4->selection_color(FL_BACKGROUND_COLOR);
                calLrf4->labeltype(FL_NO_LABEL);
                calLrf4->labelfont(0);
                calLrf4->labelsize(14);
                calLrf4->labelcolor(FL_FOREGROUND_COLOR);
                calLrf4->align(FL_ALIGN_CENTER);
                calLrf4->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf4
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab4->end();
        } // Fl_Group* tab4
        { tab5 = new Fl_Group(15, 35, 980, 260, " 5");
          tab5->labelsize(11);
          tab5->user_data((void*)(4));
          tab5->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft5 = new calImageWindow(20, 45, 320, 240);
                calLeft5->box(FL_NO_BOX);
                calLeft5->color(FL_BACKGROUND_COLOR);
                calLeft5->selection_color(FL_BACKGROUND_COLOR);
                calLeft5->labeltype(FL_NO_LABEL);
                calLeft5->labelfont(0);
                calLeft5->labelsize(14);
                calLeft5->labelcolor(FL_FOREGROUND_COLOR);
                calLeft5->align(FL_ALIGN_CENTER);
                calLeft5->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft5
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight5 = new calImageWindow(345, 45, 320, 240);
                calRight5->box(FL_NO_BOX);
                calRight5->color(FL_BACKGROUND_COLOR);
                calRight5->selection_color(FL_BACKGROUND_COLOR);
                calRight5->labeltype(FL_NO_LABEL);
                calRight5->labelfont(0);
                calRight5->labelsize(14);
                calRight5->labelcolor(FL_FOREGROUND_COLOR);
                calRight5->align(FL_ALIGN_CENTER);
                calRight5->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight5
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf5 = new calImageWindow(675, 45, 320, 240);
                calLrf5->box(FL_NO_BOX);
                calLrf5->color(FL_BACKGROUND_COLOR);
                calLrf5->selection_color(FL_BACKGROUND_COLOR);
                calLrf5->labeltype(FL_NO_LABEL);
                calLrf5->labelfont(0);
                calLrf5->labelsize(14);
                calLrf5->labelcolor(FL_FOREGROUND_COLOR);
                calLrf5->align(FL_ALIGN_CENTER);
                calLrf5->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf5
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab5->end();
        } // Fl_Group* tab5
        { tab6 = new Fl_Group(15, 35, 980, 260, " 6");
          tab6->labelsize(11);
          tab6->user_data((void*)(5));
          tab6->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft6 = new calImageWindow(20, 45, 320, 240);
                calLeft6->box(FL_NO_BOX);
                calLeft6->color(FL_BACKGROUND_COLOR);
                calLeft6->selection_color(FL_BACKGROUND_COLOR);
                calLeft6->labeltype(FL_NO_LABEL);
                calLeft6->labelfont(0);
                calLeft6->labelsize(14);
                calLeft6->labelcolor(FL_FOREGROUND_COLOR);
                calLeft6->align(FL_ALIGN_CENTER);
                calLeft6->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft6
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight6 = new calImageWindow(345, 45, 320, 240);
                calRight6->box(FL_NO_BOX);
                calRight6->color(FL_BACKGROUND_COLOR);
                calRight6->selection_color(FL_BACKGROUND_COLOR);
                calRight6->labeltype(FL_NO_LABEL);
                calRight6->labelfont(0);
                calRight6->labelsize(14);
                calRight6->labelcolor(FL_FOREGROUND_COLOR);
                calRight6->align(FL_ALIGN_CENTER);
                calRight6->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight6
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf6 = new calImageWindow(675, 45, 320, 240);
                calLrf6->box(FL_NO_BOX);
                calLrf6->color(FL_BACKGROUND_COLOR);
                calLrf6->selection_color(FL_BACKGROUND_COLOR);
                calLrf6->labeltype(FL_NO_LABEL);
                calLrf6->labelfont(0);
                calLrf6->labelsize(14);
                calLrf6->labelcolor(FL_FOREGROUND_COLOR);
                calLrf6->align(FL_ALIGN_CENTER);
                calLrf6->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf6
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab6->end();
        } // Fl_Group* tab6
        { tab7 = new Fl_Group(15, 35, 980, 260, " 7");
          tab7->labelsize(11);
          tab7->user_data((void*)(6));
          tab7->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft7 = new calImageWindow(20, 45, 320, 240);
                calLeft7->box(FL_NO_BOX);
                calLeft7->color(FL_BACKGROUND_COLOR);
                calLeft7->selection_color(FL_BACKGROUND_COLOR);
                calLeft7->labeltype(FL_NO_LABEL);
                calLeft7->labelfont(0);
                calLeft7->labelsize(14);
                calLeft7->labelcolor(FL_FOREGROUND_COLOR);
                calLeft7->align(FL_ALIGN_CENTER);
                calLeft7->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft7
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight7 = new calImageWindow(345, 45, 320, 240);
                calRight7->box(FL_NO_BOX);
                calRight7->color(FL_BACKGROUND_COLOR);
                calRight7->selection_color(FL_BACKGROUND_COLOR);
                calRight7->labeltype(FL_NO_LABEL);
                calRight7->labelfont(0);
                calRight7->labelsize(14);
                calRight7->labelcolor(FL_FOREGROUND_COLOR);
                calRight7->align(FL_ALIGN_CENTER);
                calRight7->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight7
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf7 = new calImageWindow(675, 45, 320, 240);
                calLrf7->box(FL_NO_BOX);
                calLrf7->color(FL_BACKGROUND_COLOR);
                calLrf7->selection_color(FL_BACKGROUND_COLOR);
                calLrf7->labeltype(FL_NO_LABEL);
                calLrf7->labelfont(0);
                calLrf7->labelsize(14);
                calLrf7->labelcolor(FL_FOREGROUND_COLOR);
                calLrf7->align(FL_ALIGN_CENTER);
                calLrf7->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf7
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab7->end();
        } // Fl_Group* tab7
        { tab8 = new Fl_Group(15, 35, 980, 260, " 8");
          tab8->labelsize(11);
          tab8->user_data((void*)(7));
          tab8->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft8 = new calImageWindow(20, 45, 320, 240);
                calLeft8->box(FL_NO_BOX);
                calLeft8->color(FL_BACKGROUND_COLOR);
                calLeft8->selection_color(FL_BACKGROUND_COLOR);
                calLeft8->labeltype(FL_NO_LABEL);
                calLeft8->labelfont(0);
                calLeft8->labelsize(14);
                calLeft8->labelcolor(FL_FOREGROUND_COLOR);
                calLeft8->align(FL_ALIGN_CENTER);
                calLeft8->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft8
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight8 = new calImageWindow(345, 45, 320, 240);
                calRight8->box(FL_NO_BOX);
                calRight8->color(FL_BACKGROUND_COLOR);
                calRight8->selection_color(FL_BACKGROUND_COLOR);
                calRight8->labeltype(FL_NO_LABEL);
                calRight8->labelfont(0);
                calRight8->labelsize(14);
                calRight8->labelcolor(FL_FOREGROUND_COLOR);
                calRight8->align(FL_ALIGN_CENTER);
                calRight8->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight8
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf8 = new calImageWindow(675, 45, 320, 240);
                calLrf8->box(FL_NO_BOX);
                calLrf8->color(FL_BACKGROUND_COLOR);
                calLrf8->selection_color(FL_BACKGROUND_COLOR);
                calLrf8->labeltype(FL_NO_LABEL);
                calLrf8->labelfont(0);
                calLrf8->labelsize(14);
                calLrf8->labelcolor(FL_FOREGROUND_COLOR);
                calLrf8->align(FL_ALIGN_CENTER);
                calLrf8->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf8
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab8->end();
        } // Fl_Group* tab8
        { tab9 = new Fl_Group(15, 35, 980, 260, " 9");
          tab9->labelsize(11);
          tab9->user_data((void*)(8));
          tab9->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft9 = new calImageWindow(20, 45, 320, 240);
                calLeft9->box(FL_NO_BOX);
                calLeft9->color(FL_BACKGROUND_COLOR);
                calLeft9->selection_color(FL_BACKGROUND_COLOR);
                calLeft9->labeltype(FL_NO_LABEL);
                calLeft9->labelfont(0);
                calLeft9->labelsize(14);
                calLeft9->labelcolor(FL_FOREGROUND_COLOR);
                calLeft9->align(FL_ALIGN_CENTER);
                calLeft9->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft9
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight9 = new calImageWindow(345, 45, 320, 240);
                calRight9->box(FL_NO_BOX);
                calRight9->color(FL_BACKGROUND_COLOR);
                calRight9->selection_color(FL_BACKGROUND_COLOR);
                calRight9->labeltype(FL_NO_LABEL);
                calRight9->labelfont(0);
                calRight9->labelsize(14);
                calRight9->labelcolor(FL_FOREGROUND_COLOR);
                calRight9->align(FL_ALIGN_CENTER);
                calRight9->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight9
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf9 = new calImageWindow(675, 45, 320, 240);
                calLrf9->box(FL_NO_BOX);
                calLrf9->color(FL_BACKGROUND_COLOR);
                calLrf9->selection_color(FL_BACKGROUND_COLOR);
                calLrf9->labeltype(FL_NO_LABEL);
                calLrf9->labelfont(0);
                calLrf9->labelsize(14);
                calLrf9->labelcolor(FL_FOREGROUND_COLOR);
                calLrf9->align(FL_ALIGN_CENTER);
                calLrf9->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf9
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab9->end();
        } // Fl_Group* tab9
        { tab10 = new Fl_Group(15, 35, 980, 260, " 10");
          tab10->labelsize(11);
          tab10->user_data((void*)(9));
          tab10->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft10 = new calImageWindow(20, 45, 320, 240);
                calLeft10->box(FL_NO_BOX);
                calLeft10->color(FL_BACKGROUND_COLOR);
                calLeft10->selection_color(FL_BACKGROUND_COLOR);
                calLeft10->labeltype(FL_NO_LABEL);
                calLeft10->labelfont(0);
                calLeft10->labelsize(14);
                calLeft10->labelcolor(FL_FOREGROUND_COLOR);
                calLeft10->align(FL_ALIGN_CENTER);
                calLeft10->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft10
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight10 = new calImageWindow(345, 45, 320, 240);
                calRight10->box(FL_NO_BOX);
                calRight10->color(FL_BACKGROUND_COLOR);
                calRight10->selection_color(FL_BACKGROUND_COLOR);
                calRight10->labeltype(FL_NO_LABEL);
                calRight10->labelfont(0);
                calRight10->labelsize(14);
                calRight10->labelcolor(FL_FOREGROUND_COLOR);
                calRight10->align(FL_ALIGN_CENTER);
                calRight10->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight10
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf10 = new calImageWindow(675, 45, 320, 240);
                calLrf10->box(FL_NO_BOX);
                calLrf10->color(FL_BACKGROUND_COLOR);
                calLrf10->selection_color(FL_BACKGROUND_COLOR);
                calLrf10->labeltype(FL_NO_LABEL);
                calLrf10->labelfont(0);
                calLrf10->labelsize(14);
                calLrf10->labelcolor(FL_FOREGROUND_COLOR);
                calLrf10->align(FL_ALIGN_CENTER);
                calLrf10->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf10
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab10->end();
        } // Fl_Group* tab10
        { tab11 = new Fl_Group(15, 35, 980, 260, " 11");
          tab11->labelsize(11);
          tab11->user_data((void*)(10));
          tab11->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft11 = new calImageWindow(20, 45, 320, 240);
                calLeft11->box(FL_NO_BOX);
                calLeft11->color(FL_BACKGROUND_COLOR);
                calLeft11->selection_color(FL_BACKGROUND_COLOR);
                calLeft11->labeltype(FL_NO_LABEL);
                calLeft11->labelfont(0);
                calLeft11->labelsize(14);
                calLeft11->labelcolor(FL_FOREGROUND_COLOR);
                calLeft11->align(FL_ALIGN_CENTER);
                calLeft11->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft11
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight11 = new calImageWindow(345, 45, 320, 240);
                calRight11->box(FL_NO_BOX);
                calRight11->color(FL_BACKGROUND_COLOR);
                calRight11->selection_color(FL_BACKGROUND_COLOR);
                calRight11->labeltype(FL_NO_LABEL);
                calRight11->labelfont(0);
                calRight11->labelsize(14);
                calRight11->labelcolor(FL_FOREGROUND_COLOR);
                calRight11->align(FL_ALIGN_CENTER);
                calRight11->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight11
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf11 = new calImageWindow(675, 45, 320, 240);
                calLrf11->box(FL_NO_BOX);
                calLrf11->color(FL_BACKGROUND_COLOR);
                calLrf11->selection_color(FL_BACKGROUND_COLOR);
                calLrf11->labeltype(FL_NO_LABEL);
                calLrf11->labelfont(0);
                calLrf11->labelsize(14);
                calLrf11->labelcolor(FL_FOREGROUND_COLOR);
                calLrf11->align(FL_ALIGN_CENTER);
                calLrf11->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf11
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab11->end();
        } // Fl_Group* tab11
        { tab12 = new Fl_Group(15, 35, 980, 260, " 12");
          tab12->labelsize(11);
          tab12->user_data((void*)(11));
          tab12->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft12 = new calImageWindow(20, 45, 320, 240);
                calLeft12->box(FL_NO_BOX);
                calLeft12->color(FL_BACKGROUND_COLOR);
                calLeft12->selection_color(FL_BACKGROUND_COLOR);
                calLeft12->labeltype(FL_NO_LABEL);
                calLeft12->labelfont(0);
                calLeft12->labelsize(14);
                calLeft12->labelcolor(FL_FOREGROUND_COLOR);
                calLeft12->align(FL_ALIGN_CENTER);
                calLeft12->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft12
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight12 = new calImageWindow(345, 45, 320, 240);
                calRight12->box(FL_NO_BOX);
                calRight12->color(FL_BACKGROUND_COLOR);
                calRight12->selection_color(FL_BACKGROUND_COLOR);
                calRight12->labeltype(FL_NO_LABEL);
                calRight12->labelfont(0);
                calRight12->labelsize(14);
                calRight12->labelcolor(FL_FOREGROUND_COLOR);
                calRight12->align(FL_ALIGN_CENTER);
                calRight12->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight12
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf12 = new calImageWindow(675, 45, 320, 240);
                calLrf12->box(FL_NO_BOX);
                calLrf12->color(FL_BACKGROUND_COLOR);
                calLrf12->selection_color(FL_BACKGROUND_COLOR);
                calLrf12->labeltype(FL_NO_LABEL);
                calLrf12->labelfont(0);
                calLrf12->labelsize(14);
                calLrf12->labelcolor(FL_FOREGROUND_COLOR);
                calLrf12->align(FL_ALIGN_CENTER);
                calLrf12->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf12
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab12->end();
        } // Fl_Group* tab12
        { tab13 = new Fl_Group(15, 35, 980, 260, " 13");
          tab13->labelsize(11);
          tab13->user_data((void*)(12));
          tab13->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft13 = new calImageWindow(20, 45, 320, 240);
                calLeft13->box(FL_NO_BOX);
                calLeft13->color(FL_BACKGROUND_COLOR);
                calLeft13->selection_color(FL_BACKGROUND_COLOR);
                calLeft13->labeltype(FL_NO_LABEL);
                calLeft13->labelfont(0);
                calLeft13->labelsize(14);
                calLeft13->labelcolor(FL_FOREGROUND_COLOR);
                calLeft13->align(FL_ALIGN_CENTER);
                calLeft13->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft13
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight13 = new calImageWindow(345, 45, 320, 240);
                calRight13->box(FL_NO_BOX);
                calRight13->color(FL_BACKGROUND_COLOR);
                calRight13->selection_color(FL_BACKGROUND_COLOR);
                calRight13->labeltype(FL_NO_LABEL);
                calRight13->labelfont(0);
                calRight13->labelsize(14);
                calRight13->labelcolor(FL_FOREGROUND_COLOR);
                calRight13->align(FL_ALIGN_CENTER);
                calRight13->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight13
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf13 = new calImageWindow(675, 45, 320, 240);
                calLrf13->box(FL_NO_BOX);
                calLrf13->color(FL_BACKGROUND_COLOR);
                calLrf13->selection_color(FL_BACKGROUND_COLOR);
                calLrf13->labeltype(FL_NO_LABEL);
                calLrf13->labelfont(0);
                calLrf13->labelsize(14);
                calLrf13->labelcolor(FL_FOREGROUND_COLOR);
                calLrf13->align(FL_ALIGN_CENTER);
                calLrf13->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf13
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab13->end();
        } // Fl_Group* tab13
        { tab14 = new Fl_Group(15, 35, 980, 260, " 14");
          tab14->labelsize(11);
          tab14->user_data((void*)(13));
          tab14->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft14 = new calImageWindow(20, 45, 320, 240);
                calLeft14->box(FL_NO_BOX);
                calLeft14->color(FL_BACKGROUND_COLOR);
                calLeft14->selection_color(FL_BACKGROUND_COLOR);
                calLeft14->labeltype(FL_NO_LABEL);
                calLeft14->labelfont(0);
                calLeft14->labelsize(14);
                calLeft14->labelcolor(FL_FOREGROUND_COLOR);
                calLeft14->align(FL_ALIGN_CENTER);
                calLeft14->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft14
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight14 = new calImageWindow(345, 45, 320, 240);
                calRight14->box(FL_NO_BOX);
                calRight14->color(FL_BACKGROUND_COLOR);
                calRight14->selection_color(FL_BACKGROUND_COLOR);
                calRight14->labeltype(FL_NO_LABEL);
                calRight14->labelfont(0);
                calRight14->labelsize(14);
                calRight14->labelcolor(FL_FOREGROUND_COLOR);
                calRight14->align(FL_ALIGN_CENTER);
                calRight14->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight14
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf14 = new calImageWindow(675, 45, 320, 240);
                calLrf14->box(FL_NO_BOX);
                calLrf14->color(FL_BACKGROUND_COLOR);
                calLrf14->selection_color(FL_BACKGROUND_COLOR);
                calLrf14->labeltype(FL_NO_LABEL);
                calLrf14->labelfont(0);
                calLrf14->labelsize(14);
                calLrf14->labelcolor(FL_FOREGROUND_COLOR);
                calLrf14->align(FL_ALIGN_CENTER);
                calLrf14->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf14
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab14->end();
        } // Fl_Group* tab14
        { tab15 = new Fl_Group(15, 35, 980, 260, " 15");
          tab15->labelsize(11);
          tab15->user_data((void*)(14));
          tab15->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft15 = new calImageWindow(20, 45, 320, 240);
                calLeft15->box(FL_NO_BOX);
                calLeft15->color(FL_BACKGROUND_COLOR);
                calLeft15->selection_color(FL_BACKGROUND_COLOR);
                calLeft15->labeltype(FL_NO_LABEL);
                calLeft15->labelfont(0);
                calLeft15->labelsize(14);
                calLeft15->labelcolor(FL_FOREGROUND_COLOR);
                calLeft15->align(FL_ALIGN_CENTER);
                calLeft15->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft15
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight15 = new calImageWindow(345, 45, 320, 240);
                calRight15->box(FL_NO_BOX);
                calRight15->color(FL_BACKGROUND_COLOR);
                calRight15->selection_color(FL_BACKGROUND_COLOR);
                calRight15->labeltype(FL_NO_LABEL);
                calRight15->labelfont(0);
                calRight15->labelsize(14);
                calRight15->labelcolor(FL_FOREGROUND_COLOR);
                calRight15->align(FL_ALIGN_CENTER);
                calRight15->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight15
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf15 = new calImageWindow(675, 45, 320, 240);
                calLrf15->box(FL_NO_BOX);
                calLrf15->color(FL_BACKGROUND_COLOR);
                calLrf15->selection_color(FL_BACKGROUND_COLOR);
                calLrf15->labeltype(FL_NO_LABEL);
                calLrf15->labelfont(0);
                calLrf15->labelsize(14);
                calLrf15->labelcolor(FL_FOREGROUND_COLOR);
                calLrf15->align(FL_ALIGN_CENTER);
                calLrf15->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf15
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab15->end();
        } // Fl_Group* tab15
        { tab16 = new Fl_Group(15, 35, 980, 260, " 16");
          tab16->labelsize(11);
          tab16->user_data((void*)(15));
          tab16->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft16 = new calImageWindow(20, 45, 320, 240);
                calLeft16->box(FL_NO_BOX);
                calLeft16->color(FL_BACKGROUND_COLOR);
                calLeft16->selection_color(FL_BACKGROUND_COLOR);
                calLeft16->labeltype(FL_NO_LABEL);
                calLeft16->labelfont(0);
                calLeft16->labelsize(14);
                calLeft16->labelcolor(FL_FOREGROUND_COLOR);
                calLeft16->align(FL_ALIGN_CENTER);
                calLeft16->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft16
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight16 = new calImageWindow(345, 45, 320, 240);
                calRight16->box(FL_NO_BOX);
                calRight16->color(FL_BACKGROUND_COLOR);
                calRight16->selection_color(FL_BACKGROUND_COLOR);
                calRight16->labeltype(FL_NO_LABEL);
                calRight16->labelfont(0);
                calRight16->labelsize(14);
                calRight16->labelcolor(FL_FOREGROUND_COLOR);
                calRight16->align(FL_ALIGN_CENTER);
                calRight16->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight16
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf16 = new calImageWindow(675, 45, 320, 240);
                calLrf16->box(FL_NO_BOX);
                calLrf16->color(FL_BACKGROUND_COLOR);
                calLrf16->selection_color(FL_BACKGROUND_COLOR);
                calLrf16->labeltype(FL_NO_LABEL);
                calLrf16->labelfont(0);
                calLrf16->labelsize(14);
                calLrf16->labelcolor(FL_FOREGROUND_COLOR);
                calLrf16->align(FL_ALIGN_CENTER);
                calLrf16->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf16
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab16->end();
        } // Fl_Group* tab16
        { tab17 = new Fl_Group(15, 35, 980, 260, " 17");
          tab17->labelsize(11);
          tab17->user_data((void*)(16));
          tab17->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft17 = new calImageWindow(20, 45, 320, 240);
                calLeft17->box(FL_NO_BOX);
                calLeft17->color(FL_BACKGROUND_COLOR);
                calLeft17->selection_color(FL_BACKGROUND_COLOR);
                calLeft17->labeltype(FL_NO_LABEL);
                calLeft17->labelfont(0);
                calLeft17->labelsize(14);
                calLeft17->labelcolor(FL_FOREGROUND_COLOR);
                calLeft17->align(FL_ALIGN_CENTER);
                calLeft17->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft17
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight17 = new calImageWindow(345, 45, 320, 240);
                calRight17->box(FL_NO_BOX);
                calRight17->color(FL_BACKGROUND_COLOR);
                calRight17->selection_color(FL_BACKGROUND_COLOR);
                calRight17->labeltype(FL_NO_LABEL);
                calRight17->labelfont(0);
                calRight17->labelsize(14);
                calRight17->labelcolor(FL_FOREGROUND_COLOR);
                calRight17->align(FL_ALIGN_CENTER);
                calRight17->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight17
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf17 = new calImageWindow(675, 45, 320, 240);
                calLrf17->box(FL_NO_BOX);
                calLrf17->color(FL_BACKGROUND_COLOR);
                calLrf17->selection_color(FL_BACKGROUND_COLOR);
                calLrf17->labeltype(FL_NO_LABEL);
                calLrf17->labelfont(0);
                calLrf17->labelsize(14);
                calLrf17->labelcolor(FL_FOREGROUND_COLOR);
                calLrf17->align(FL_ALIGN_CENTER);
                calLrf17->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf17
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab17->end();
        } // Fl_Group* tab17
        { tab18 = new Fl_Group(15, 35, 980, 260, " 18");
          tab18->labelsize(11);
          tab18->user_data((void*)(17));
          tab18->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft18 = new calImageWindow(20, 45, 320, 240);
                calLeft18->box(FL_NO_BOX);
                calLeft18->color(FL_BACKGROUND_COLOR);
                calLeft18->selection_color(FL_BACKGROUND_COLOR);
                calLeft18->labeltype(FL_NO_LABEL);
                calLeft18->labelfont(0);
                calLeft18->labelsize(14);
                calLeft18->labelcolor(FL_FOREGROUND_COLOR);
                calLeft18->align(FL_ALIGN_CENTER);
                calLeft18->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft18
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight18 = new calImageWindow(345, 45, 320, 240);
                calRight18->box(FL_NO_BOX);
                calRight18->color(FL_BACKGROUND_COLOR);
                calRight18->selection_color(FL_BACKGROUND_COLOR);
                calRight18->labeltype(FL_NO_LABEL);
                calRight18->labelfont(0);
                calRight18->labelsize(14);
                calRight18->labelcolor(FL_FOREGROUND_COLOR);
                calRight18->align(FL_ALIGN_CENTER);
                calRight18->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight18
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf18 = new calImageWindow(675, 45, 320, 240);
                calLrf18->box(FL_NO_BOX);
                calLrf18->color(FL_BACKGROUND_COLOR);
                calLrf18->selection_color(FL_BACKGROUND_COLOR);
                calLrf18->labeltype(FL_NO_LABEL);
                calLrf18->labelfont(0);
                calLrf18->labelsize(14);
                calLrf18->labelcolor(FL_FOREGROUND_COLOR);
                calLrf18->align(FL_ALIGN_CENTER);
                calLrf18->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf18
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab18->end();
        } // Fl_Group* tab18
        { tab19 = new Fl_Group(15, 35, 980, 260, " 19");
          tab19->labelsize(11);
          tab19->user_data((void*)(18));
          tab19->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft19 = new calImageWindow(20, 45, 320, 240);
                calLeft19->box(FL_NO_BOX);
                calLeft19->color(FL_BACKGROUND_COLOR);
                calLeft19->selection_color(FL_BACKGROUND_COLOR);
                calLeft19->labeltype(FL_NO_LABEL);
                calLeft19->labelfont(0);
                calLeft19->labelsize(14);
                calLeft19->labelcolor(FL_FOREGROUND_COLOR);
                calLeft19->align(FL_ALIGN_CENTER);
                calLeft19->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft19
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight19 = new calImageWindow(345, 45, 320, 240);
                calRight19->box(FL_NO_BOX);
                calRight19->color(FL_BACKGROUND_COLOR);
                calRight19->selection_color(FL_BACKGROUND_COLOR);
                calRight19->labeltype(FL_NO_LABEL);
                calRight19->labelfont(0);
                calRight19->labelsize(14);
                calRight19->labelcolor(FL_FOREGROUND_COLOR);
                calRight19->align(FL_ALIGN_CENTER);
                calRight19->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight19
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf19 = new calImageWindow(675, 45, 320, 240);
                calLrf19->box(FL_NO_BOX);
                calLrf19->color(FL_BACKGROUND_COLOR);
                calLrf19->selection_color(FL_BACKGROUND_COLOR);
                calLrf19->labeltype(FL_NO_LABEL);
                calLrf19->labelfont(0);
                calLrf19->labelsize(14);
                calLrf19->labelcolor(FL_FOREGROUND_COLOR);
                calLrf19->align(FL_ALIGN_CENTER);
                calLrf19->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf19
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab19->end();
        } // Fl_Group* tab19
        { tab20 = new Fl_Group(15, 35, 980, 260, " 20");
          tab20->labelsize(11);
          tab20->user_data((void*)(19));
          tab20->hide();
          { Fl_Group* o = new Fl_Group(20, 45, 975, 245);
            { Fl_Group* o = new Fl_Group(20, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(20, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft20 = new calImageWindow(20, 45, 320, 240);
                calLeft20->box(FL_NO_BOX);
                calLeft20->color(FL_BACKGROUND_COLOR);
                calLeft20->selection_color(FL_BACKGROUND_COLOR);
                calLeft20->labeltype(FL_NO_LABEL);
                calLeft20->labelfont(0);
                calLeft20->labelsize(14);
                calLeft20->labelcolor(FL_FOREGROUND_COLOR);
                calLeft20->align(FL_ALIGN_CENTER);
                calLeft20->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft20
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(345, 45, 320, 240);
              { Fl_Box* o = new Fl_Box(345, 50, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight20 = new calImageWindow(345, 45, 320, 240);
                calRight20->box(FL_NO_BOX);
                calRight20->color(FL_BACKGROUND_COLOR);
                calRight20->selection_color(FL_BACKGROUND_COLOR);
                calRight20->labeltype(FL_NO_LABEL);
                calRight20->labelfont(0);
                calRight20->labelsize(14);
                calRight20->labelcolor(FL_FOREGROUND_COLOR);
                calRight20->align(FL_ALIGN_CENTER);
                calRight20->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight20
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(675, 45, 320, 245);
              { Fl_Box* o = new Fl_Box(675, 45, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLrf20 = new calImageWindow(675, 45, 320, 240);
                calLrf20->box(FL_NO_BOX);
                calLrf20->color(FL_BACKGROUND_COLOR);
                calLrf20->selection_color(FL_BACKGROUND_COLOR);
                calLrf20->labeltype(FL_NO_LABEL);
                calLrf20->labelfont(0);
                calLrf20->labelsize(14);
                calLrf20->labelcolor(FL_FOREGROUND_COLOR);
                calLrf20->align(FL_ALIGN_CENTER);
                calLrf20->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLrf20
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab20->end();
        } // Fl_Group* tab20
        window_tab->end();
      } // Fl_Tabs* window_tab
      { Fl_Group* o = new Fl_Group(410, 30, 815, 300);
        { Fl_Button* o = load_button = new Fl_Button(1020, 105, 90, 25, "Load all 3");
          load_button->down_box(FL_DOWN_BOX);
          load_button->labelsize(11);
          load_button->callback((Fl_Callback*)cal_load_cb);
          o->user_data((void *)this);
        } // Fl_Button* load_button
        { Fl_Button* o = save_button = new Fl_Button(1020, 175, 90, 25, "Save");
          save_button->down_box(FL_DOWN_BOX);
          save_button->labelsize(11);
          save_button->callback((Fl_Callback*)cal_save_image_cb);
          o->user_data((void *)this);
        } // Fl_Button* save_button
        { Fl_Button* o = capture_button = new Fl_Button(1020, 40, 90, 25, "Capture");
          capture_button->down_box(FL_DOWN_BOX);
          capture_button->labelsize(11);
          capture_button->callback((Fl_Callback*)cal_capture_cb);
          o->user_data((void *)this);
        } // Fl_Button* capture_button
        { Fl_Button* o = save_all_button = new Fl_Button(1020, 200, 90, 25, "Save All");
          save_all_button->down_box(FL_DOWN_BOX);
          save_all_button->labelsize(11);
          save_all_button->callback((Fl_Callback*)cal_save_all_cb);
          o->user_data((void *)this);
        } // Fl_Button* save_all_button
        { Fl_Button* o = delete_button = new Fl_Button(1020, 240, 90, 25, "Delete");
          delete_button->down_box(FL_DOWN_BOX);
          delete_button->labelsize(11);
          delete_button->callback((Fl_Callback*)cal_delete_image);
          o->user_data((void *)this);
        } // Fl_Button* delete_button
        { Fl_Button* o = load_left_button = new Fl_Button(1020, 80, 30, 25, "Left");
          load_left_button->down_box(FL_DOWN_BOX);
          load_left_button->labelsize(11);
          load_left_button->callback((Fl_Callback*)cal_load_left_cb);
          o->user_data((void *)this);
        } // Fl_Button* load_left_button
        { Fl_Button* o = load_right_button = new Fl_Button(1050, 80, 30, 25, "Right");
          load_right_button->down_box(FL_DOWN_BOX);
          load_right_button->labelsize(11);
          load_right_button->callback((Fl_Callback*)cal_load_right_cb);
          o->user_data((void *)this);
        } // Fl_Button* load_right_button
        // begin jdc
        { Fl_Button* o = load_lrf_button = new Fl_Button(1080, 80, 30, 25, "LRF");
          load_lrf_button->down_box(FL_DOWN_BOX);
          load_lrf_button->labelsize(11);
          load_lrf_button->callback((Fl_Callback*)cal_load_lrf_cb);
          o->user_data((void *)this);
        } // Fl_Button* load_lrf_button
        // end jdc
        { Fl_Button* o = load_seq_button = new Fl_Button(1020, 130, 90, 25, "Load sequence");
          load_seq_button->down_box(FL_DOWN_BOX);
          load_seq_button->labelsize(11);
          load_seq_button->callback((Fl_Callback*)cal_load_seq_cb);
          o->user_data((void *)this);
        } // Fl_Button* load_seq_button
        { Fl_Button* o = stereo_button = new Fl_Button(1020, 300, 90, 25, "Stereo");
          stereo_button->down_box(FL_DOWN_BOX);
          stereo_button->labelsize(11);
          stereo_button->callback((Fl_Callback*)do_stereo_cb);
          o->user_data((void *)this);
        } // Fl_Button* stereo_button
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Group* o
    { info_message = new Fl_Output(20, 305, 490, 25);
      info_message->box(FL_BORDER_BOX);
      info_message->color(FL_BACKGROUND_COLOR);
      info_message->labelsize(11);
      info_message->textsize(11);
    } // Fl_Output* info_message
    { Fl_Group* o = new Fl_Group(20, 305, 655, 85);
    { Fl_Button* o = calibrate_button = new Fl_Button(525, 305, 95, 25, "Calibrate");
      calibrate_button->down_box(FL_DOWN_BOX);
      calibrate_button->labelsize(11);
      calibrate_button->callback((Fl_Callback*)cal_calibrate_stlrf_cb);
      o->user_data((void *)this);
    } // Fl_Button* calibrate_button
#if 0
    { Fl_Button* o = calibrate_stlrf_button = new Fl_Button(635, 305, 100, 25, "Calibrate St+LRF");
      calibrate_stlrf_button->down_box(FL_DOWN_BOX);
      calibrate_stlrf_button->labelsize(11);
      calibrate_stlrf_button->callback((Fl_Callback*)cal_calibrate_stlrf_cb);
      o->user_data((void *)this);
    } // Fl_Button* calibrate_stlrf_button
#endif
      { Fl_Button* o = save_params_button = new Fl_Button(625, 305, 95, 25, "Save params");
        save_params_button->down_box(FL_DOWN_BOX);
        save_params_button->labelsize(11);
        save_params_button->callback((Fl_Callback*)cal_save_params_cb);
        o->user_data((void *)this);
      } // Fl_Button* save_params_button
      { Fl_Button* o = done_button = new Fl_Button(525, 335, 95, 25, "Done");
        done_button->down_box(FL_DOWN_BOX);
        done_button->labelsize(11);
        done_button->callback((Fl_Callback*)cal_ok_cb);
        o->user_data((void *)this);
      } // Fl_Button* done_button
      { Fl_Button* o = epi_button = new Fl_Button(625, 335, 95, 25, "Epi check");
        epi_button->down_box(FL_DOWN_BOX);
        epi_button->labelsize(11);
        epi_button->callback((Fl_Callback*)cal_epipolar_cb);
        o->user_data((void *)this);
      } // Fl_Button* epi_button
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(20, 340, 490, 60);
      { Fl_Box* o = new Fl_Box(20, 340, 290, 50);
        o->box(FL_ENGRAVED_FRAME);
      } // Fl_Box* o
      { fixed_aspect_button = new Fl_Check_Button(215, 340, 25, 25, "Fixed Aspect");
        fixed_aspect_button->down_box(FL_DOWN_BOX);
        fixed_aspect_button->value(1);
        fixed_aspect_button->labelsize(11);
        fixed_aspect_button->callback((Fl_Callback*)cal_fixed_aspect_cb);
      } // Fl_Check_Button* fixed_aspect_button
      { fixed_kappa2_button = new Fl_Check_Button(30, 345, 25, 25, "Kappa2");
        fixed_kappa2_button->down_box(FL_DOWN_BOX);
        fixed_kappa2_button->value(1);
        fixed_kappa2_button->labelsize(11);
        fixed_kappa2_button->callback((Fl_Callback*)cal_fixed_kappa2_cb);
      } // Fl_Check_Button* fixed_kappa2_button
      { fixed_kappa3_button = new Fl_Check_Button(85, 345, 25, 25, "Kappa3");
        fixed_kappa3_button->down_box(FL_DOWN_BOX);
        fixed_kappa3_button->labelsize(11);
        fixed_kappa3_button->callback((Fl_Callback*)cal_fixed_kappa3_cb);
      } // Fl_Check_Button* fixed_kappa3_button
      { fixed_tau_button = new Fl_Check_Button(140, 345, 25, 25, "Tau1, Tau2");
        fixed_tau_button->down_box(FL_DOWN_BOX);
        fixed_tau_button->labelsize(11);
        fixed_tau_button->callback((Fl_Callback*)cal_fixed_tau_cb);
      } // Fl_Check_Button* fixed_tau_button
      { zero_disparity_button = new Fl_Check_Button(215, 355, 25, 25, "Zero disparity");
        zero_disparity_button->down_box(FL_DOWN_BOX);
        zero_disparity_button->value(1);
        zero_disparity_button->labelsize(11);
        zero_disparity_button->callback((Fl_Callback*)cal_zero_disparity_cb);
      } // Fl_Check_Button* zero_disparity_button
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(345, 340, 175, 270);
      { Fl_Box* o = new Fl_Box(345, 340, 150, 50, "label");
        o->box(FL_ENGRAVED_FRAME);
        o->labeltype(FL_NO_LABEL);
      } // Fl_Box* o
      { user_check_size = new Fl_Value_Input(360, 360, 30, 20, "Size mm");
        user_check_size->labelsize(11);
        user_check_size->maximum(1000);
        user_check_size->step(1);
        user_check_size->value(100);
        user_check_size->textsize(11);
        user_check_size->callback((Fl_Callback*)cal_check_size_cb);
        user_check_size->align(FL_ALIGN_TOP);
      } // Fl_Value_Input* user_check_size
      { user_check_x = new Fl_Value_Input(405, 360, 30, 20, "Ints X");
        user_check_x->labelsize(11);
        user_check_x->maximum(100);
        user_check_x->step(1);
        user_check_x->value(8);
        user_check_x->textsize(11);
        user_check_x->callback((Fl_Callback*)cal_check_x_cb);
        user_check_x->align(FL_ALIGN_TOP);
      } // Fl_Value_Input* user_check_x
      { user_check_y = new Fl_Value_Input(445, 360, 30, 20, "Ints Y");
        user_check_y->labelsize(11);
        user_check_y->maximum(100);
        user_check_y->step(1);
        user_check_y->value(6);
        user_check_y->textsize(11);
        user_check_y->callback((Fl_Callback*)cal_check_y_cb);
        user_check_y->align(FL_ALIGN_TOP);
      } // Fl_Value_Input* user_check_y
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(525, 365, 250, 30);
      { Fl_Box* o = new Fl_Box(525, 365, 250, 30, "label");
        o->box(FL_ENGRAVED_FRAME);
        o->labeltype(FL_NO_LABEL);
      } // Fl_Box* o
      { user_check_size = new Fl_Value_Input(745, 370, 20, 20, "RANSAC inlier threshold (1/10 pixels)");
        user_check_size->labelsize(11);
        user_check_size->maximum(1000);
        user_check_size->step(1);
        user_check_size->value(99);  // for 9.9 pixels
        user_check_size->textsize(11);
        user_check_size->callback((Fl_Callback*)cal_ransac_threshold_cb);
        user_check_size->align(FL_ALIGN_LEFT);
      } // Fl_Value_Input* ransac thrshold
      o->end();
    } // Fl_Group* o   
    stereo_lrf_calibration->end();
  } // Fl_Window* stereo_lrf_calibration
}
