#!/usr/bin/env ruby
require "#{`#{ENV['ROS_ROOT']}/rospack latest yamlgraph`}/lib/yamlgraph/ygl.rb"
g = YAMLGraph.new
g.node 'laser_viewer/laser_viewer', {'launch'=>'xterm'}
g.node 'hokuyourg_player/hokuyourg'#, {'launch'=>'xterm'}
g.flow 'hokuyourg:scans', 'laser_viewer:scans'
YAMLGraphLauncher.new.launch g

