#!/usr/bin/env ruby
require 'fileutils.rb'

if !ENV['ROS_ROOT']
  puts "ahhh no ros_root"
  exit
end

libjpeg_path = `#{ENV['ROS_ROOT']}/rospack find stair__ijg_libjpeg`
puts "libjpeg path = #{libjpeg_path}"
if libjpeg_path.length <= 1
  puts "couldn't find libjpeg. try running this from your ROS_ROOT directory:"
  puts "   ./rospack install stair__ijg_libjpeg"
  exit
end

sdl_path = `#{ENV['ROS_ROOT']}/rospack find stair__sdl`
puts "sdl path = #{sdl_path}"
if sdl_path.length <= 1
  puts "couldn't find SDL. try running this from your ROS_ROOT directory:"
  puts "   ./rospack install stair__sdl"
  exit
end

pkg_path = File.expand_path($0).split('/')
pkg_path = pkg_path[0,pkg_path.length-1].join('/')
puts "package path: [#{pkg_path}]"
if pkg_path.length < 1
  puts "woah! package path looks scary. something isn't right. bailing..."
  exit
end

Dir.chdir(pkg_path)
# TODO make sure we got there

if ARGV.length == 0 || ARGV[0] == 'update'
  puts "extracting SDL_image ========================="
  system "tar xzvf SDL_image-1.2.6.tar.gz"
  Dir.mkdir 'bin' if !File.exists? 'bin'
  Dir.mkdir 'lib' if !File.exists? 'lib'
  puts "configuring SDL_image ============================"
  Dir.chdir "#{pkg_path}/SDL_image-1.2.6"
  system("./configure --with-sdl-prefix=\"#{sdl_path}\" --prefix=${PWD}/.. CPPFLAGS=\"-I#{libjpeg_path}/include\" LDFLAGS=\"-L#{libjpeg_path}/lib\"")
# TODO check for blowups after configure
  puts "making SDL_image ================================="
  system("make")
  puts "moving files around ============================"
  system("make install")
  # change the include paths so it works with our packaging system...
  system "sed -e 's:SDL.h:SDL/SDL.h:' -e 's:SDL_version.h:SDL/SDL_version.h:' -e 's:begin_code.h:SDL/begin_code.h:' -e 's:close_code.h:SDL/close_code.h:' <../include/SDL/SDL_image.h >../include/SDL/SDL_image_mod.h"
  system "mv ../include/SDL/SDL_image_mod.h ../include/SDL/SDL_image.h"
# TODO check for make errors
  puts "done! hooray! =================================="
elsif ARGV[0] == 'clean'
  Dir.chdir "#{pkg_path}"
  system("rm -rf bin")
  system("rm -rf include")
  system("rm -rf lib")
  system "rm -rf SDL_image-1.2.6"
  puts "done!"
else
  puts "unknown parameter: #{ARGV[0]}"
end

