PKG = pr2Core

CFLAGS = -g -Wall -Iinclude `rospack --lang=cpp --attrib=cflags export $(PKG)`

LDFLAGS = `rospack --lang=cpp --attrib=lflags export $(PKG)`

LIB = 

all: $(LIB)

clean:
	#rm -f *.o *.a lib/*.a

