#!/usr/bin/env ruby
$:.push(`rospack find rubot`.strip)
require 'rubot/stair1.rb'

r = Stair1.new
#r.navigate(37.91, 8.53, -2.00)
#r.opendoor 0.3
r.navigate(36.498, 4.86, 2.645)
#r.move_arm('move_for_camera')
#r.borgscan
r.navigate(37.034, 3.236, -2.045)
#r.borgscan
r.navigate(38.560, 2.619, -0.588)
#r.borgscan
r.navigate(38.625, 3.593, 0.887)
#r.borgscan
#r.move_arm('move_to_upright')
#r.navigate(36.287, 9.568, -2.114)
#r.opendoor -0.3
r.navigate(34.809, 8.026, 2.544)
#r.move_arm('move_for_camera')
#r.borgscan
r.navigate(33.738, 6.483, 2.565)
#r.borgscan
r.navigate(33.429, 5.834, -2.29)
#r.borgscan
#r.move_arm('move_to_upright')
r.navigate(33.592, 11.224, 2.494)

