#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Fri Mar 20 14:03:53 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_2 = wx.Panel(self, -1)
        self.sizer_3_staticbox = wx.StaticBox(self.panel_2, -1, "Test")
        self.panel_1 = wx.Panel(self, -1)
        self.exposure_label_copy = wx.StaticText(self.panel_1, -1, "Exposure")
        self.checkbox_1 = wx.CheckBox(self.panel_1, -1, "auto")
        self.exposure_slider_copy = wx.Slider(self.panel_1, -1, 0, 0, 10)
        self.exposure_spin_copy = wx.SpinCtrl(self.panel_1, -1, "", min=0, max=100)
        self.exposure_label_copy_copy = wx.StaticText(self.panel_2, -1, "Exposure")
        self.text_ctrl_1 = wx.TextCtrl(self.panel_2, -1, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_CHECKBOX, self.onCheckbox, self.checkbox_1)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.onExposureSlider, self.exposure_slider_copy)
        self.Bind(wx.EVT_SPINCTRL, self.onExposureSpin, self.exposure_spin_copy)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.exposure_label_copy.SetMinSize((100, -1))
        self.exposure_label_copy_copy.SetMinSize((100, -1))
        self.text_ctrl_1.SetMinSize((100, -1))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.HORIZONTAL)
        sizer_2_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2_copy_copy_copy.Add(self.exposure_label_copy, 0, 0, 0)
        sizer_2_copy_copy_copy.Add(self.checkbox_1, 0, 0, 0)
        sizer_2_copy_copy_copy.Add(self.exposure_slider_copy, 1, 0, 0)
        sizer_2_copy_copy_copy.Add(self.exposure_spin_copy, 0, 0, 0)
        self.panel_1.SetSizer(sizer_2_copy_copy_copy)
        sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        sizer_3.Add(self.exposure_label_copy_copy, 0, 0, 0)
        sizer_3.Add((20, 20), 1, 0, 0)
        sizer_3.Add(self.text_ctrl_1, 0, 0, 0)
        self.panel_2.SetSizer(sizer_3)
        sizer_2.Add(self.panel_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

    def onExposureSlider(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `onExposureSlider' not implemented!"
        event.Skip()

    def onExposureSpin(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `onExposureSpin' not implemented!"
        event.Skip()

    def onCheckbox(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `onCheckbox' not implemented"
        event.Skip()

    def onEdit(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `onEdit' not implemented"
        event.Skip()

# end of class MyFrame


class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MyFrame(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
