#!/usr/bin/env ruby
(puts "aaaaaaaa no ROS_ROOT"; exit) if !ENV['ROS_ROOT']
require "#{`#{ENV['ROS_ROOT']}/rospack latest yamlgraph`}/lib/yamlgraph/ygl.rb"
g = YAMLGraph.new
g.param 'servo.host', '192.168.1.38'
g.param 'axis_cam_wget_polled.host', '192.168.1.90'
g.param 'sharks.start', '-25.0'
g.param 'sharks.end', '25.0'
g.param 'sharks.step', '0.5'
g.node  'ipdcmot/servo', {'launch'=>'xterm'}
g.node  'sharks/sharks2', {'launch'=>'xterm'}
g.node  'axis_cam/axis_cam_wget_polled', {'launch'=>'xterm'}
g.flow  'sharks:getpos_request', 'servo:getpos_blocking'
g.flow  'servo:getpos_result', 'sharks:getpos_result'
g.flow  'sharks:setpos_request', 'servo:setpos_blocking'
g.flow  'servo:setpos_result', 'sharks:setpos_result'
g.flow  'sharks:shutter', 'axis_cam_wget_polled:shutter'
g.flow  'axis_cam_wget_polled:image', 'sharks:image'
YAMLGraphLauncher.new.launch g

