/* auto-generated by genmsg_cpp from /u/ethand/ros/ros-pkg/sandbox/follower/msg/MoveHeadGoal.msg.  Do not edit! */
package ros.pkg.follower.msg;


import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;
public  class MoveHeadGoal extends ros.communication.Message
{


  public MoveHeadGoal() {
 super();

  }
  public static java.lang.String __s_getDataType() { return "follower/MoveHeadGoal"; }
  public static java.lang.String __s_getMD5Sum() { return "d41d8cd98f00b204e9800998ecf8427e"; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public MoveHeadGoal clone() {
    MoveHeadGoal clone = (MoveHeadGoal)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof MoveHeadGoal)) throw new RuntimeException("Invalid Type");
    MoveHeadGoal __m2 = (MoveHeadGoal) __m;
    }

  public int serializationLength() 
  {
    int __l = 0;
    return __l;
  }
  public void serialize(OutputStream os, int seq) throws IOException {
  }
  public void deserialize(InputStream is)  throws IOException  {
  }
}

