#!/usr/bin/env ruby
require "#{`#{ENV['ROS_ROOT']}/rospack latest yamlgraph`}/lib/yamlgraph/ygl.rb"
g = YAMLGraph.new
g.param 'axis_cam_wget.host', '192.168.1.90'
g.node 'axis_cam/axis_cam_wget', {'launch'=>'xterm'}
g.node 'image_viewer/image_viewer', {'launch'=>'xterm'}
g.flow 'axis_cam_wget:image', 'image_viewer:image'
YAMLGraphLauncher.new.launch g

