// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "stereogui.h"

Fl_Menu_Item stereogui::menu_[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Load Images...", 0,  (Fl_Callback*)load_images_cb, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save Images...", 0,  (Fl_Callback*)save_images_cb, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Load Params...", 0,  (Fl_Callback*)load_params_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save Params...", 0,  (Fl_Callback*)save_params_cb, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Exit", 0,  (Fl_Callback*)do_exit_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Video...", 0,  (Fl_Callback*)video_window_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Stereo...", 0,  (Fl_Callback*)stereo_window_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Calibrate...", 0,  (Fl_Callback*)cal_window_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Debug...", 0,  (Fl_Callback*)debug_window_cb, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item stereogui::menu_Size[] = {
 {"320x240", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"640x480", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"1280x960", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item stereogui::menu_Rate[] = {
 {"30 Hz", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"15 Hz", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {"7.5 Hz", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 11, 0},
 {0,0,0,0,0,0,0,0,0}
};

stereogui::stereogui() {
  { stereo_calibration = new Fl_Window(655, 305, "Open STereo");
    stereo_calibration->labelsize(11);
    stereo_calibration->user_data((void*)(this));
    { info_message = new Fl_Output(5, 275, 490, 25);
      info_message->box(FL_BORDER_BOX);
      info_message->color(FL_BACKGROUND_COLOR);
      info_message->labelsize(11);
      info_message->textsize(11);
    } // Fl_Output* info_message
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 680, 20);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { Fl_Group* o = new Fl_Group(5, 25, 645, 245);
      { Fl_Group* o = new Fl_Group(5, 25, 320, 245);
        { Fl_Box* o = new Fl_Box(5, 25, 320, 240);
          o->box(FL_EMBOSSED_FRAME);
          o->labeltype(FL_NO_LABEL);
        } // Fl_Box* o
        { mainLeft = new calImageWindow(5, 25, 320, 240);
          mainLeft->box(FL_NO_BOX);
          mainLeft->color(FL_BACKGROUND_COLOR);
          mainLeft->selection_color(FL_BACKGROUND_COLOR);
          mainLeft->labeltype(FL_NO_LABEL);
          mainLeft->labelfont(0);
          mainLeft->labelsize(14);
          mainLeft->labelcolor(FL_FOREGROUND_COLOR);
          mainLeft->align(FL_ALIGN_CENTER);
          mainLeft->when(FL_WHEN_RELEASE);
        } // calImageWindow* mainLeft
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(330, 25, 320, 245);
        { Fl_Box* o = new Fl_Box(330, 25, 320, 240);
          o->box(FL_EMBOSSED_FRAME);
          o->labeltype(FL_NO_LABEL);
        } // Fl_Box* o
        { mainRight = new calImageWindow(330, 25, 320, 240);
          mainRight->box(FL_NO_BOX);
          mainRight->color(FL_BACKGROUND_COLOR);
          mainRight->selection_color(FL_BACKGROUND_COLOR);
          mainRight->labeltype(FL_NO_LABEL);
          mainRight->labelfont(0);
          mainRight->labelsize(14);
          mainRight->labelcolor(FL_FOREGROUND_COLOR);
          mainRight->align(FL_ALIGN_CENTER);
          mainRight->when(FL_WHEN_RELEASE);
        } // calImageWindow* mainRight
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Group* o
    stereo_calibration->end();
  } // Fl_Window* stereo_calibration
  { cal_images = new Fl_Window(675, 295, "Calibration images");
    cal_images->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(5, 0, 855, 375);
      { window_tab = new Fl_Tabs(5, 0, 665, 295);
        window_tab->box(FL_UP_BOX);
        window_tab->labeltype(FL_NO_LABEL);
        { tab1 = new Fl_Group(10, 35, 660, 250, " 1 ");
          tab1->labelsize(11);
          tab1->user_data((void*)(1));
          tab1->hide();
          tab1->deactivate();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 35, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft1 = new calImageWindow(15, 35, 320, 240);
                calLeft1->box(FL_NO_BOX);
                calLeft1->color(FL_BACKGROUND_COLOR);
                calLeft1->selection_color(FL_BACKGROUND_COLOR);
                calLeft1->labeltype(FL_NO_LABEL);
                calLeft1->labelfont(0);
                calLeft1->labelsize(14);
                calLeft1->labelcolor(FL_FOREGROUND_COLOR);
                calLeft1->align(FL_ALIGN_CENTER);
                calLeft1->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft1
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(340, 35, 320, 240);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight1 = new calImageWindow(340, 35, 320, 240);
                calRight1->box(FL_NO_BOX);
                calRight1->color(FL_BACKGROUND_COLOR);
                calRight1->selection_color(FL_BACKGROUND_COLOR);
                calRight1->labeltype(FL_NO_LABEL);
                calRight1->labelfont(0);
                calRight1->labelsize(14);
                calRight1->labelcolor(FL_FOREGROUND_COLOR);
                calRight1->align(FL_ALIGN_CENTER);
                calRight1->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight1
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab1->end();
        } // Fl_Group* tab1
        { tab2 = new Fl_Group(10, 25, 660, 260, " 2");
          tab2->labelsize(11);
          tab2->user_data((void*)(2));
          tab2->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft2 = new calImageWindow(15, 35, 320, 240);
                calLeft2->box(FL_NO_BOX);
                calLeft2->color(FL_BACKGROUND_COLOR);
                calLeft2->selection_color(FL_BACKGROUND_COLOR);
                calLeft2->labeltype(FL_NO_LABEL);
                calLeft2->labelfont(0);
                calLeft2->labelsize(14);
                calLeft2->labelcolor(FL_FOREGROUND_COLOR);
                calLeft2->align(FL_ALIGN_CENTER);
                calLeft2->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft2
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight2 = new calImageWindow(340, 35, 320, 240);
                calRight2->box(FL_NO_BOX);
                calRight2->color(FL_BACKGROUND_COLOR);
                calRight2->selection_color(FL_BACKGROUND_COLOR);
                calRight2->labeltype(FL_NO_LABEL);
                calRight2->labelfont(0);
                calRight2->labelsize(14);
                calRight2->labelcolor(FL_FOREGROUND_COLOR);
                calRight2->align(FL_ALIGN_CENTER);
                calRight2->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight2
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab2->end();
        } // Fl_Group* tab2
        { tab3 = new Fl_Group(10, 25, 660, 260, " 3");
          tab3->labelsize(11);
          tab3->user_data((void*)(3));
          tab3->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft3 = new calImageWindow(15, 35, 320, 240);
                calLeft3->box(FL_NO_BOX);
                calLeft3->color(FL_BACKGROUND_COLOR);
                calLeft3->selection_color(FL_BACKGROUND_COLOR);
                calLeft3->labeltype(FL_NO_LABEL);
                calLeft3->labelfont(0);
                calLeft3->labelsize(14);
                calLeft3->labelcolor(FL_FOREGROUND_COLOR);
                calLeft3->align(FL_ALIGN_CENTER);
                calLeft3->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft3
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight3 = new calImageWindow(340, 35, 320, 240);
                calRight3->box(FL_NO_BOX);
                calRight3->color(FL_BACKGROUND_COLOR);
                calRight3->selection_color(FL_BACKGROUND_COLOR);
                calRight3->labeltype(FL_NO_LABEL);
                calRight3->labelfont(0);
                calRight3->labelsize(14);
                calRight3->labelcolor(FL_FOREGROUND_COLOR);
                calRight3->align(FL_ALIGN_CENTER);
                calRight3->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight3
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab3->end();
        } // Fl_Group* tab3
        { tab4 = new Fl_Group(10, 25, 660, 260, " 4");
          tab4->labelsize(11);
          tab4->user_data((void*)(4));
          tab4->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft4 = new calImageWindow(15, 35, 320, 240);
                calLeft4->box(FL_NO_BOX);
                calLeft4->color(FL_BACKGROUND_COLOR);
                calLeft4->selection_color(FL_BACKGROUND_COLOR);
                calLeft4->labeltype(FL_NO_LABEL);
                calLeft4->labelfont(0);
                calLeft4->labelsize(14);
                calLeft4->labelcolor(FL_FOREGROUND_COLOR);
                calLeft4->align(FL_ALIGN_CENTER);
                calLeft4->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft4
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight4 = new calImageWindow(340, 35, 320, 240);
                calRight4->box(FL_NO_BOX);
                calRight4->color(FL_BACKGROUND_COLOR);
                calRight4->selection_color(FL_BACKGROUND_COLOR);
                calRight4->labeltype(FL_NO_LABEL);
                calRight4->labelfont(0);
                calRight4->labelsize(14);
                calRight4->labelcolor(FL_FOREGROUND_COLOR);
                calRight4->align(FL_ALIGN_CENTER);
                calRight4->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight4
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab4->end();
        } // Fl_Group* tab4
        { tab5 = new Fl_Group(10, 25, 660, 260, " 5");
          tab5->labelsize(11);
          tab5->user_data((void*)(5));
          tab5->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft5 = new calImageWindow(15, 35, 320, 240);
                calLeft5->box(FL_NO_BOX);
                calLeft5->color(FL_BACKGROUND_COLOR);
                calLeft5->selection_color(FL_BACKGROUND_COLOR);
                calLeft5->labeltype(FL_NO_LABEL);
                calLeft5->labelfont(0);
                calLeft5->labelsize(14);
                calLeft5->labelcolor(FL_FOREGROUND_COLOR);
                calLeft5->align(FL_ALIGN_CENTER);
                calLeft5->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft5
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight5 = new calImageWindow(340, 35, 320, 240);
                calRight5->box(FL_NO_BOX);
                calRight5->color(FL_BACKGROUND_COLOR);
                calRight5->selection_color(FL_BACKGROUND_COLOR);
                calRight5->labeltype(FL_NO_LABEL);
                calRight5->labelfont(0);
                calRight5->labelsize(14);
                calRight5->labelcolor(FL_FOREGROUND_COLOR);
                calRight5->align(FL_ALIGN_CENTER);
                calRight5->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight5
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab5->end();
        } // Fl_Group* tab5
        { tab6 = new Fl_Group(10, 25, 660, 260, " 6");
          tab6->labelsize(11);
          tab6->user_data((void*)(6));
          tab6->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft6 = new calImageWindow(15, 35, 320, 240);
                calLeft6->box(FL_NO_BOX);
                calLeft6->color(FL_BACKGROUND_COLOR);
                calLeft6->selection_color(FL_BACKGROUND_COLOR);
                calLeft6->labeltype(FL_NO_LABEL);
                calLeft6->labelfont(0);
                calLeft6->labelsize(14);
                calLeft6->labelcolor(FL_FOREGROUND_COLOR);
                calLeft6->align(FL_ALIGN_CENTER);
                calLeft6->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft6
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight6 = new calImageWindow(340, 35, 320, 240);
                calRight6->box(FL_NO_BOX);
                calRight6->color(FL_BACKGROUND_COLOR);
                calRight6->selection_color(FL_BACKGROUND_COLOR);
                calRight6->labeltype(FL_NO_LABEL);
                calRight6->labelfont(0);
                calRight6->labelsize(14);
                calRight6->labelcolor(FL_FOREGROUND_COLOR);
                calRight6->align(FL_ALIGN_CENTER);
                calRight6->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight6
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab6->end();
        } // Fl_Group* tab6
        { tab7 = new Fl_Group(10, 25, 660, 260, " 7");
          tab7->labelsize(11);
          tab7->user_data((void*)(7));
          tab7->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft7 = new calImageWindow(15, 35, 320, 240);
                calLeft7->box(FL_NO_BOX);
                calLeft7->color(FL_BACKGROUND_COLOR);
                calLeft7->selection_color(FL_BACKGROUND_COLOR);
                calLeft7->labeltype(FL_NO_LABEL);
                calLeft7->labelfont(0);
                calLeft7->labelsize(14);
                calLeft7->labelcolor(FL_FOREGROUND_COLOR);
                calLeft7->align(FL_ALIGN_CENTER);
                calLeft7->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft7
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight7 = new calImageWindow(340, 35, 320, 240);
                calRight7->box(FL_NO_BOX);
                calRight7->color(FL_BACKGROUND_COLOR);
                calRight7->selection_color(FL_BACKGROUND_COLOR);
                calRight7->labeltype(FL_NO_LABEL);
                calRight7->labelfont(0);
                calRight7->labelsize(14);
                calRight7->labelcolor(FL_FOREGROUND_COLOR);
                calRight7->align(FL_ALIGN_CENTER);
                calRight7->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight7
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab7->end();
        } // Fl_Group* tab7
        { tab8 = new Fl_Group(10, 25, 660, 260, " 8");
          tab8->labelsize(11);
          tab8->user_data((void*)(8));
          tab8->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft8 = new calImageWindow(15, 35, 320, 240);
                calLeft8->box(FL_NO_BOX);
                calLeft8->color(FL_BACKGROUND_COLOR);
                calLeft8->selection_color(FL_BACKGROUND_COLOR);
                calLeft8->labeltype(FL_NO_LABEL);
                calLeft8->labelfont(0);
                calLeft8->labelsize(14);
                calLeft8->labelcolor(FL_FOREGROUND_COLOR);
                calLeft8->align(FL_ALIGN_CENTER);
                calLeft8->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft8
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight8 = new calImageWindow(340, 35, 320, 240);
                calRight8->box(FL_NO_BOX);
                calRight8->color(FL_BACKGROUND_COLOR);
                calRight8->selection_color(FL_BACKGROUND_COLOR);
                calRight8->labeltype(FL_NO_LABEL);
                calRight8->labelfont(0);
                calRight8->labelsize(14);
                calRight8->labelcolor(FL_FOREGROUND_COLOR);
                calRight8->align(FL_ALIGN_CENTER);
                calRight8->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight8
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab8->end();
        } // Fl_Group* tab8
        { tab9 = new Fl_Group(10, 25, 660, 260, " 9");
          tab9->labelsize(11);
          tab9->user_data((void*)(9));
          tab9->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft9 = new calImageWindow(15, 35, 320, 240);
                calLeft9->box(FL_NO_BOX);
                calLeft9->color(FL_BACKGROUND_COLOR);
                calLeft9->selection_color(FL_BACKGROUND_COLOR);
                calLeft9->labeltype(FL_NO_LABEL);
                calLeft9->labelfont(0);
                calLeft9->labelsize(14);
                calLeft9->labelcolor(FL_FOREGROUND_COLOR);
                calLeft9->align(FL_ALIGN_CENTER);
                calLeft9->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft9
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight9 = new calImageWindow(340, 35, 320, 240);
                calRight9->box(FL_NO_BOX);
                calRight9->color(FL_BACKGROUND_COLOR);
                calRight9->selection_color(FL_BACKGROUND_COLOR);
                calRight9->labeltype(FL_NO_LABEL);
                calRight9->labelfont(0);
                calRight9->labelsize(14);
                calRight9->labelcolor(FL_FOREGROUND_COLOR);
                calRight9->align(FL_ALIGN_CENTER);
                calRight9->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight9
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab9->end();
        } // Fl_Group* tab9
        { tab10 = new Fl_Group(10, 25, 660, 260, " 10");
          tab10->labelsize(11);
          tab10->user_data((void*)(10));
          tab10->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft10 = new calImageWindow(15, 35, 320, 240);
                calLeft10->box(FL_NO_BOX);
                calLeft10->color(FL_BACKGROUND_COLOR);
                calLeft10->selection_color(FL_BACKGROUND_COLOR);
                calLeft10->labeltype(FL_NO_LABEL);
                calLeft10->labelfont(0);
                calLeft10->labelsize(14);
                calLeft10->labelcolor(FL_FOREGROUND_COLOR);
                calLeft10->align(FL_ALIGN_CENTER);
                calLeft10->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft10
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight10 = new calImageWindow(340, 35, 320, 240);
                calRight10->box(FL_NO_BOX);
                calRight10->color(FL_BACKGROUND_COLOR);
                calRight10->selection_color(FL_BACKGROUND_COLOR);
                calRight10->labeltype(FL_NO_LABEL);
                calRight10->labelfont(0);
                calRight10->labelsize(14);
                calRight10->labelcolor(FL_FOREGROUND_COLOR);
                calRight10->align(FL_ALIGN_CENTER);
                calRight10->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight10
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab10->end();
        } // Fl_Group* tab10
        { tab11 = new Fl_Group(10, 25, 660, 260, " 11");
          tab11->labelsize(11);
          tab11->user_data((void*)(11));
          tab11->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft11 = new calImageWindow(15, 35, 320, 240);
                calLeft11->box(FL_NO_BOX);
                calLeft11->color(FL_BACKGROUND_COLOR);
                calLeft11->selection_color(FL_BACKGROUND_COLOR);
                calLeft11->labeltype(FL_NO_LABEL);
                calLeft11->labelfont(0);
                calLeft11->labelsize(14);
                calLeft11->labelcolor(FL_FOREGROUND_COLOR);
                calLeft11->align(FL_ALIGN_CENTER);
                calLeft11->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft11
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight11 = new calImageWindow(340, 35, 320, 240);
                calRight11->box(FL_NO_BOX);
                calRight11->color(FL_BACKGROUND_COLOR);
                calRight11->selection_color(FL_BACKGROUND_COLOR);
                calRight11->labeltype(FL_NO_LABEL);
                calRight11->labelfont(0);
                calRight11->labelsize(14);
                calRight11->labelcolor(FL_FOREGROUND_COLOR);
                calRight11->align(FL_ALIGN_CENTER);
                calRight11->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight11
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab11->end();
        } // Fl_Group* tab11
        { tab12 = new Fl_Group(10, 25, 660, 260, " 12");
          tab12->labelsize(11);
          tab12->user_data((void*)(12));
          tab12->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft12 = new calImageWindow(15, 35, 320, 240);
                calLeft12->box(FL_NO_BOX);
                calLeft12->color(FL_BACKGROUND_COLOR);
                calLeft12->selection_color(FL_BACKGROUND_COLOR);
                calLeft12->labeltype(FL_NO_LABEL);
                calLeft12->labelfont(0);
                calLeft12->labelsize(14);
                calLeft12->labelcolor(FL_FOREGROUND_COLOR);
                calLeft12->align(FL_ALIGN_CENTER);
                calLeft12->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft12
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight12 = new calImageWindow(340, 35, 320, 240);
                calRight12->box(FL_NO_BOX);
                calRight12->color(FL_BACKGROUND_COLOR);
                calRight12->selection_color(FL_BACKGROUND_COLOR);
                calRight12->labeltype(FL_NO_LABEL);
                calRight12->labelfont(0);
                calRight12->labelsize(14);
                calRight12->labelcolor(FL_FOREGROUND_COLOR);
                calRight12->align(FL_ALIGN_CENTER);
                calRight12->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight12
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab12->end();
        } // Fl_Group* tab12
        { tab13 = new Fl_Group(10, 25, 660, 260, " 13");
          tab13->labelsize(11);
          tab13->user_data((void*)(13));
          tab13->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft13 = new calImageWindow(15, 35, 320, 240);
                calLeft13->box(FL_NO_BOX);
                calLeft13->color(FL_BACKGROUND_COLOR);
                calLeft13->selection_color(FL_BACKGROUND_COLOR);
                calLeft13->labeltype(FL_NO_LABEL);
                calLeft13->labelfont(0);
                calLeft13->labelsize(14);
                calLeft13->labelcolor(FL_FOREGROUND_COLOR);
                calLeft13->align(FL_ALIGN_CENTER);
                calLeft13->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft13
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight13 = new calImageWindow(340, 35, 320, 240);
                calRight13->box(FL_NO_BOX);
                calRight13->color(FL_BACKGROUND_COLOR);
                calRight13->selection_color(FL_BACKGROUND_COLOR);
                calRight13->labeltype(FL_NO_LABEL);
                calRight13->labelfont(0);
                calRight13->labelsize(14);
                calRight13->labelcolor(FL_FOREGROUND_COLOR);
                calRight13->align(FL_ALIGN_CENTER);
                calRight13->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight13
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab13->end();
        } // Fl_Group* tab13
        { tab14 = new Fl_Group(10, 25, 660, 260, " 14");
          tab14->labelsize(11);
          tab14->user_data((void*)(14));
          tab14->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft14 = new calImageWindow(15, 35, 320, 240);
                calLeft14->box(FL_NO_BOX);
                calLeft14->color(FL_BACKGROUND_COLOR);
                calLeft14->selection_color(FL_BACKGROUND_COLOR);
                calLeft14->labeltype(FL_NO_LABEL);
                calLeft14->labelfont(0);
                calLeft14->labelsize(14);
                calLeft14->labelcolor(FL_FOREGROUND_COLOR);
                calLeft14->align(FL_ALIGN_CENTER);
                calLeft14->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft14
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight14 = new calImageWindow(340, 35, 320, 240);
                calRight14->box(FL_NO_BOX);
                calRight14->color(FL_BACKGROUND_COLOR);
                calRight14->selection_color(FL_BACKGROUND_COLOR);
                calRight14->labeltype(FL_NO_LABEL);
                calRight14->labelfont(0);
                calRight14->labelsize(14);
                calRight14->labelcolor(FL_FOREGROUND_COLOR);
                calRight14->align(FL_ALIGN_CENTER);
                calRight14->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight14
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab14->end();
        } // Fl_Group* tab14
        { tab15 = new Fl_Group(10, 25, 660, 260, " 15");
          tab15->labelsize(11);
          tab15->user_data((void*)(15));
          tab15->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft15 = new calImageWindow(15, 35, 320, 240);
                calLeft15->box(FL_NO_BOX);
                calLeft15->color(FL_BACKGROUND_COLOR);
                calLeft15->selection_color(FL_BACKGROUND_COLOR);
                calLeft15->labeltype(FL_NO_LABEL);
                calLeft15->labelfont(0);
                calLeft15->labelsize(14);
                calLeft15->labelcolor(FL_FOREGROUND_COLOR);
                calLeft15->align(FL_ALIGN_CENTER);
                calLeft15->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft15
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight15 = new calImageWindow(340, 35, 320, 240);
                calRight15->box(FL_NO_BOX);
                calRight15->color(FL_BACKGROUND_COLOR);
                calRight15->selection_color(FL_BACKGROUND_COLOR);
                calRight15->labeltype(FL_NO_LABEL);
                calRight15->labelfont(0);
                calRight15->labelsize(14);
                calRight15->labelcolor(FL_FOREGROUND_COLOR);
                calRight15->align(FL_ALIGN_CENTER);
                calRight15->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight15
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab15->end();
        } // Fl_Group* tab15
        { tab16 = new Fl_Group(10, 25, 660, 260, " 16");
          tab16->labelsize(11);
          tab16->user_data((void*)(16));
          tab16->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft16 = new calImageWindow(15, 35, 320, 240);
                calLeft16->box(FL_NO_BOX);
                calLeft16->color(FL_BACKGROUND_COLOR);
                calLeft16->selection_color(FL_BACKGROUND_COLOR);
                calLeft16->labeltype(FL_NO_LABEL);
                calLeft16->labelfont(0);
                calLeft16->labelsize(14);
                calLeft16->labelcolor(FL_FOREGROUND_COLOR);
                calLeft16->align(FL_ALIGN_CENTER);
                calLeft16->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft16
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight16 = new calImageWindow(340, 35, 320, 240);
                calRight16->box(FL_NO_BOX);
                calRight16->color(FL_BACKGROUND_COLOR);
                calRight16->selection_color(FL_BACKGROUND_COLOR);
                calRight16->labeltype(FL_NO_LABEL);
                calRight16->labelfont(0);
                calRight16->labelsize(14);
                calRight16->labelcolor(FL_FOREGROUND_COLOR);
                calRight16->align(FL_ALIGN_CENTER);
                calRight16->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight16
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab16->end();
        } // Fl_Group* tab16
        { tab17 = new Fl_Group(10, 25, 660, 260, " 17");
          tab17->labelsize(11);
          tab17->user_data((void*)(17));
          tab17->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft17 = new calImageWindow(15, 35, 320, 240);
                calLeft17->box(FL_NO_BOX);
                calLeft17->color(FL_BACKGROUND_COLOR);
                calLeft17->selection_color(FL_BACKGROUND_COLOR);
                calLeft17->labeltype(FL_NO_LABEL);
                calLeft17->labelfont(0);
                calLeft17->labelsize(14);
                calLeft17->labelcolor(FL_FOREGROUND_COLOR);
                calLeft17->align(FL_ALIGN_CENTER);
                calLeft17->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft17
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight17 = new calImageWindow(340, 35, 320, 240);
                calRight17->box(FL_NO_BOX);
                calRight17->color(FL_BACKGROUND_COLOR);
                calRight17->selection_color(FL_BACKGROUND_COLOR);
                calRight17->labeltype(FL_NO_LABEL);
                calRight17->labelfont(0);
                calRight17->labelsize(14);
                calRight17->labelcolor(FL_FOREGROUND_COLOR);
                calRight17->align(FL_ALIGN_CENTER);
                calRight17->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight17
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab17->end();
        } // Fl_Group* tab17
        { tab18 = new Fl_Group(10, 25, 660, 260, " 18");
          tab18->labelsize(11);
          tab18->user_data((void*)(18));
          tab18->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft18 = new calImageWindow(15, 35, 320, 240);
                calLeft18->box(FL_NO_BOX);
                calLeft18->color(FL_BACKGROUND_COLOR);
                calLeft18->selection_color(FL_BACKGROUND_COLOR);
                calLeft18->labeltype(FL_NO_LABEL);
                calLeft18->labelfont(0);
                calLeft18->labelsize(14);
                calLeft18->labelcolor(FL_FOREGROUND_COLOR);
                calLeft18->align(FL_ALIGN_CENTER);
                calLeft18->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft18
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight18 = new calImageWindow(340, 35, 320, 240);
                calRight18->box(FL_NO_BOX);
                calRight18->color(FL_BACKGROUND_COLOR);
                calRight18->selection_color(FL_BACKGROUND_COLOR);
                calRight18->labeltype(FL_NO_LABEL);
                calRight18->labelfont(0);
                calRight18->labelsize(14);
                calRight18->labelcolor(FL_FOREGROUND_COLOR);
                calRight18->align(FL_ALIGN_CENTER);
                calRight18->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight18
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab18->end();
        } // Fl_Group* tab18
        { tab19 = new Fl_Group(10, 25, 660, 260, " 19");
          tab19->labelsize(11);
          tab19->user_data((void*)(19));
          tab19->hide();
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft19 = new calImageWindow(15, 35, 320, 240);
                calLeft19->box(FL_NO_BOX);
                calLeft19->color(FL_BACKGROUND_COLOR);
                calLeft19->selection_color(FL_BACKGROUND_COLOR);
                calLeft19->labeltype(FL_NO_LABEL);
                calLeft19->labelfont(0);
                calLeft19->labelsize(14);
                calLeft19->labelcolor(FL_FOREGROUND_COLOR);
                calLeft19->align(FL_ALIGN_CENTER);
                calLeft19->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft19
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight19 = new calImageWindow(340, 35, 320, 240);
                calRight19->box(FL_NO_BOX);
                calRight19->color(FL_BACKGROUND_COLOR);
                calRight19->selection_color(FL_BACKGROUND_COLOR);
                calRight19->labeltype(FL_NO_LABEL);
                calRight19->labelfont(0);
                calRight19->labelsize(14);
                calRight19->labelcolor(FL_FOREGROUND_COLOR);
                calRight19->align(FL_ALIGN_CENTER);
                calRight19->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight19
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab19->end();
        } // Fl_Group* tab19
        { tab20 = new Fl_Group(10, 25, 660, 260, " 20");
          tab20->labelsize(11);
          tab20->user_data((void*)(20));
          { Fl_Group* o = new Fl_Group(15, 35, 645, 245);
            { Fl_Group* o = new Fl_Group(15, 35, 320, 245);
              { Fl_Box* o = new Fl_Box(15, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calLeft20 = new calImageWindow(15, 35, 320, 240);
                calLeft20->box(FL_NO_BOX);
                calLeft20->color(FL_BACKGROUND_COLOR);
                calLeft20->selection_color(FL_BACKGROUND_COLOR);
                calLeft20->labeltype(FL_NO_LABEL);
                calLeft20->labelfont(0);
                calLeft20->labelsize(14);
                calLeft20->labelcolor(FL_FOREGROUND_COLOR);
                calLeft20->align(FL_ALIGN_CENTER);
                calLeft20->when(FL_WHEN_RELEASE);
              } // calImageWindow* calLeft20
              o->end();
            } // Fl_Group* o
            { Fl_Group* o = new Fl_Group(340, 35, 320, 240);
              { Fl_Box* o = new Fl_Box(340, 40, 320, 235);
                o->box(FL_EMBOSSED_FRAME);
                o->labeltype(FL_NO_LABEL);
              } // Fl_Box* o
              { calRight20 = new calImageWindow(340, 35, 320, 240);
                calRight20->box(FL_NO_BOX);
                calRight20->color(FL_BACKGROUND_COLOR);
                calRight20->selection_color(FL_BACKGROUND_COLOR);
                calRight20->labeltype(FL_NO_LABEL);
                calRight20->labelfont(0);
                calRight20->labelsize(14);
                calRight20->labelcolor(FL_FOREGROUND_COLOR);
                calRight20->align(FL_ALIGN_CENTER);
                calRight20->when(FL_WHEN_RELEASE);
              } // calImageWindow* calRight20
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          tab20->end();
        } // Fl_Group* tab20
        window_tab->end();
      } // Fl_Tabs* window_tab
      o->end();
    } // Fl_Group* o
    cal_images->end();
  } // Fl_Window* cal_images
  { cal_window = new Fl_Window(305, 340, "Calibration");
    cal_window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(10, 20, 160, 300);
      { Fl_Button* o = capture_button = new Fl_Button(10, 20, 90, 25, "Capture");
        capture_button->down_box(FL_DOWN_BOX);
        capture_button->labelsize(11);
        capture_button->callback((Fl_Callback*)cal_capture_cb);
        o->user_data((void *)this);
      } // Fl_Button* capture_button
      { Fl_Button* o = load_button = new Fl_Button(10, 130, 90, 25, "Load both");
        load_button->down_box(FL_DOWN_BOX);
        load_button->labelsize(11);
        load_button->callback((Fl_Callback*)cal_load_cb);
        o->user_data((void *)this);
      } // Fl_Button* load_button
      { Fl_Button* o = save_button = new Fl_Button(10, 200, 90, 25, "Save");
        save_button->down_box(FL_DOWN_BOX);
        save_button->labelsize(11);
        save_button->callback((Fl_Callback*)cal_save_image_cb);
        o->user_data((void *)this);
      } // Fl_Button* save_button
      { Fl_Button* o = save_all_button = new Fl_Button(10, 225, 90, 25, "Save All");
        save_all_button->down_box(FL_DOWN_BOX);
        save_all_button->labelsize(11);
        save_all_button->callback((Fl_Callback*)cal_save_all_cb);
        o->user_data((void *)this);
      } // Fl_Button* save_all_button
      { Fl_Button* o = delete_button = new Fl_Button(10, 265, 90, 25, "Delete");
        delete_button->down_box(FL_DOWN_BOX);
        delete_button->labelsize(11);
        delete_button->callback((Fl_Callback*)cal_delete_image);
        o->user_data((void *)this);
      } // Fl_Button* delete_button
      { Fl_Button* o = load_left_button = new Fl_Button(10, 105, 45, 25, "Load L");
        load_left_button->down_box(FL_DOWN_BOX);
        load_left_button->labelsize(11);
        load_left_button->callback((Fl_Callback*)cal_load_left_cb);
        o->user_data((void *)this);
      } // Fl_Button* load_left_button
      { Fl_Button* o = load_right_button = new Fl_Button(55, 105, 45, 25, "Load R");
        load_right_button->down_box(FL_DOWN_BOX);
        load_right_button->labelsize(11);
        load_right_button->callback((Fl_Callback*)cal_load_right_cb);
        o->user_data((void *)this);
      } // Fl_Button* load_right_button
      { Fl_Button* o = load_seq_button = new Fl_Button(10, 155, 90, 25, "Load sequence");
        load_seq_button->down_box(FL_DOWN_BOX);
        load_seq_button->labelsize(11);
        load_seq_button->callback((Fl_Callback*)cal_load_seq_cb);
        o->user_data((void *)this);
      } // Fl_Button* load_seq_button
      { track_button = new Fl_Light_Button(10, 55, 100, 25, "Track chessboard");
        track_button->labelsize(11);
        track_button->callback((Fl_Callback*)do_track_cb);
        Fl_Group::current()->resizable(track_button);
      } // Fl_Light_Button* track_button
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(130, 200, 175, 55);
      { Fl_Box* o = new Fl_Box(130, 200, 150, 50, "label");
        o->box(FL_ENGRAVED_FRAME);
        o->labeltype(FL_NO_LABEL);
      } // Fl_Box* o
      { user_check_size = new Fl_Value_Input(145, 220, 30, 20, "Size mm");
        user_check_size->labelsize(11);
        user_check_size->maximum(1000);
        user_check_size->step(1);
        user_check_size->value(100);
        user_check_size->textsize(11);
        user_check_size->callback((Fl_Callback*)cal_check_size_cb);
        user_check_size->align(FL_ALIGN_TOP);
      } // Fl_Value_Input* user_check_size
      { user_check_x = new Fl_Value_Input(190, 220, 30, 20, "Ints X");
        user_check_x->labelsize(11);
        user_check_x->maximum(100);
        user_check_x->step(1);
        user_check_x->value(8);
        user_check_x->textsize(11);
        user_check_x->callback((Fl_Callback*)cal_check_x_cb);
        user_check_x->align(FL_ALIGN_TOP);
      } // Fl_Value_Input* user_check_x
      { user_check_y = new Fl_Value_Input(230, 220, 30, 20, "Ints Y");
        user_check_y->labelsize(11);
        user_check_y->maximum(100);
        user_check_y->step(1);
        user_check_y->value(6);
        user_check_y->textsize(11);
        user_check_y->callback((Fl_Callback*)cal_check_y_cb);
        user_check_y->align(FL_ALIGN_TOP);
      } // Fl_Value_Input* user_check_y
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(120, 20, 165, 290);
      { Fl_Button* o = calibrate_button = new Fl_Button(135, 20, 75, 25, "Calibrate");
        calibrate_button->down_box(FL_DOWN_BOX);
        calibrate_button->labelsize(11);
        calibrate_button->callback((Fl_Callback*)cal_calibrate_cb);
        o->user_data((void *)this);
      } // Fl_Button* calibrate_button
      { Fl_Button* o = save_params_button = new Fl_Button(220, 20, 65, 25, "Save params");
        save_params_button->down_box(FL_DOWN_BOX);
        save_params_button->labelsize(11);
        save_params_button->callback((Fl_Callback*)cal_save_params_cb);
        o->user_data((void *)this);
      } // Fl_Button* save_params_button
      { Fl_Button* o = done_button = new Fl_Button(135, 50, 60, 25, "Done");
        done_button->down_box(FL_DOWN_BOX);
        done_button->labelsize(11);
        done_button->callback((Fl_Callback*)cal_ok_cb);
        o->user_data((void *)this);
      } // Fl_Button* done_button
      { Fl_Button* o = epi_button = new Fl_Button(220, 50, 60, 25, "Epi check");
        epi_button->down_box(FL_DOWN_BOX);
        epi_button->labelsize(11);
        epi_button->callback((Fl_Callback*)cal_epipolar_cb);
        o->user_data((void *)this);
      } // Fl_Button* epi_button
      { Fl_Button* o = upload_params_button = new Fl_Button(130, 270, 130, 40, "Upload params");
        upload_params_button->down_box(FL_DOWN_BOX);
        upload_params_button->callback((Fl_Callback*)cal_upload_params_cb);
        o->user_data((void *)this);
      } // Fl_Button* upload_params_button
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(125, 105, 180, 95);
      { Fl_Box* o = new Fl_Box(130, 105, 170, 85);
        o->box(FL_ENGRAVED_FRAME);
      } // Fl_Box* o
      { fixed_aspect_button = new Fl_Check_Button(210, 130, 85, 25, "Fixed Aspect");
        fixed_aspect_button->down_box(FL_DOWN_BOX);
        fixed_aspect_button->value(1);
        fixed_aspect_button->labelsize(11);
        fixed_aspect_button->callback((Fl_Callback*)cal_fixed_aspect_cb);
      } // Fl_Check_Button* fixed_aspect_button
      { fixed_kappa2_button = new Fl_Check_Button(135, 110, 25, 25, "Kappa2");
        fixed_kappa2_button->down_box(FL_DOWN_BOX);
        fixed_kappa2_button->value(1);
        fixed_kappa2_button->labelsize(11);
        fixed_kappa2_button->callback((Fl_Callback*)cal_fixed_kappa2_cb);
      } // Fl_Check_Button* fixed_kappa2_button
      { fixed_kappa3_button = new Fl_Check_Button(135, 130, 25, 25, "Kappa3");
        fixed_kappa3_button->down_box(FL_DOWN_BOX);
        fixed_kappa3_button->labelsize(11);
        fixed_kappa3_button->callback((Fl_Callback*)cal_fixed_kappa3_cb);
      } // Fl_Check_Button* fixed_kappa3_button
      { fixed_tau_button = new Fl_Check_Button(135, 150, 25, 25, "Tau1, Tau2");
        fixed_tau_button->down_box(FL_DOWN_BOX);
        fixed_tau_button->labelsize(11);
        fixed_tau_button->callback((Fl_Callback*)cal_fixed_tau_cb);
      } // Fl_Check_Button* fixed_tau_button
      { zero_disparity_button = new Fl_Check_Button(210, 110, 85, 25, "Zero disparity");
        zero_disparity_button->down_box(FL_DOWN_BOX);
        zero_disparity_button->value(1);
        zero_disparity_button->labelsize(11);
        zero_disparity_button->callback((Fl_Callback*)cal_zero_disparity_cb);
      } // Fl_Check_Button* zero_disparity_button
      o->end();
    } // Fl_Group* o
    cal_window->end();
  } // Fl_Window* cal_window
  { stereo_window = new Fl_Window(265, 260, "Stereo");
    stereo_window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(20, 135, 285, 120);
      { Fl_Box* o = new Fl_Box(20, 135, 115, 85, "label");
        o->box(FL_ENGRAVED_FRAME);
        o->labeltype(FL_NO_LABEL);
      } // Fl_Box* o
      { Fl_Counter* o = new Fl_Counter(70, 140, 55, 20, "Unique:");
        o->type(1);
        o->labelsize(11);
        o->minimum(0);
        o->maximum(100);
        o->step(1);
        o->value(30);
        o->callback((Fl_Callback*)unique_cb);
        o->align(FL_ALIGN_LEFT);
      } // Fl_Counter* o
      { Fl_Counter* o = new Fl_Counter(70, 165, 55, 20, "Texture:");
        o->type(1);
        o->labelsize(11);
        o->minimum(0);
        o->maximum(100);
        o->step(1);
        o->value(30);
        o->callback((Fl_Callback*)texture_cb);
        o->align(FL_ALIGN_LEFT);
      } // Fl_Counter* o
      { Fl_Counter* o = new Fl_Counter(70, 190, 55, 20, "Speckle:");
        o->type(1);
        o->labelsize(11);
        o->minimum(0);
        o->maximum(100);
        o->step(1);
        o->value(30);
        o->callback((Fl_Callback*)speckle_cb);
        o->align(FL_ALIGN_LEFT);
      } // Fl_Counter* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(20, 30, 285, 170);
      { Fl_Box* o = new Fl_Box(20, 30, 120, 85);
        o->box(FL_ENGRAVED_FRAME);
      } // Fl_Box* o
      { Fl_Counter* o = new Fl_Counter(75, 35, 55, 20, "Disparity:");
        o->type(1);
        o->labelsize(11);
        o->minimum(16);
        o->maximum(128);
        o->step(16);
        o->value(64);
        o->callback((Fl_Callback*)disparity_cb);
        o->align(FL_ALIGN_LEFT);
      } // Fl_Counter* o
      { Fl_Counter* o = new Fl_Counter(75, 60, 55, 20, "Window:");
        o->type(1);
        o->labelsize(11);
        o->minimum(7);
        o->maximum(21);
        o->step(1);
        o->value(15);
        o->callback((Fl_Callback*)corrsize_cb);
        o->align(FL_ALIGN_LEFT);
      } // Fl_Counter* o
      { Fl_Counter* o = new Fl_Counter(75, 85, 55, 20, "X off:");
        o->type(1);
        o->labelsize(11);
        o->minimum(-4);
        o->maximum(128);
        o->step(1);
        o->callback((Fl_Callback*)xoff_cb);
        o->align(FL_ALIGN_LEFT);
      } // Fl_Counter* o
      { Fl_Light_Button* o = rectify_button = new Fl_Light_Button(160, 35, 75, 25, "Do Rectify");
        rectify_button->box(FL_THIN_UP_BOX);
        rectify_button->labelsize(11);
        rectify_button->callback((Fl_Callback*)do_rectify_cb);
        o->user_data((void *)this);
      } // Fl_Light_Button* rectify_button
      { Fl_Light_Button* o = stereo_button = new Fl_Light_Button(160, 65, 75, 25, "Do Stereo");
        stereo_button->box(FL_THIN_UP_BOX);
        stereo_button->labelsize(11);
        stereo_button->callback((Fl_Callback*)do_stereo_cb);
        o->user_data((void *)this);
      } // Fl_Light_Button* stereo_button
      { Fl_Light_Button* o = x3d_button = new Fl_Light_Button(160, 95, 75, 25, "Do 3D");
        x3d_button->box(FL_THIN_UP_BOX);
        x3d_button->labelsize(11);
        x3d_button->callback((Fl_Callback*)do_3d_cb);
        o->user_data((void *)this);
      } // Fl_Light_Button* x3d_button
      o->end();
    } // Fl_Group* o
    stereo_window->end();
  } // Fl_Window* stereo_window
  { video_window = new Fl_Window(425, 205, "Video");
    video_window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(20, 85, 285, 170);
      { Fl_Box* o = new Fl_Box(20, 125, 135, 70, "label");
        o->box(FL_ENGRAVED_FRAME);
        o->labeltype(FL_NO_LABEL);
      } // Fl_Box* o
      { Fl_Choice* o = new Fl_Choice(50, 135, 90, 20, "Size");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)video_size_cb);
        o->menu(menu_Size);
      } // Fl_Choice* o
      { Fl_Choice* o = new Fl_Choice(50, 165, 90, 20, "Rate");
        o->down_box(FL_BORDER_BOX);
        o->labelsize(11);
        o->callback((Fl_Callback*)video_rate_cb);
        o->menu(menu_Rate);
      } // Fl_Choice* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(20, 25, 295, 170);
      { Fl_Box* o = new Fl_Box(20, 25, 200, 85);
        o->box(FL_ENGRAVED_FRAME);
        o->labelsize(11);
      } // Fl_Box* o
      { video_button = new Fl_Light_Button(30, 70, 50, 25, "Video");
        video_button->labelsize(11);
        video_button->callback((Fl_Callback*)do_video_cb);
      } // Fl_Light_Button* video_button
      { cam_select = new Fl_Choice(60, 35, 145, 20, "Cam");
        cam_select->down_box(FL_BORDER_BOX);
        cam_select->labelsize(11);
        cam_select->callback((Fl_Callback*)video_dev_cb);
      } // Fl_Choice* cam_select
      { color_button = new Fl_Light_Button(100, 70, 45, 25, "Color");
        color_button->labelsize(11);
        color_button->callback((Fl_Callback*)do_color_cb);
      } // Fl_Light_Button* color_button
      { stoc_button = new Fl_Light_Button(160, 70, 45, 25, "STOC");
        stoc_button->labelsize(11);
        stoc_button->callback((Fl_Callback*)do_stoc_cb);
      } // Fl_Light_Button* stoc_button
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(190, 40, 215, 185);
      { exposure_val = new Fl_Slider(265, 40, 20, 130, "Exposure");
        exposure_val->type(4);
        exposure_val->labelsize(11);
        exposure_val->minimum(100);
        exposure_val->maximum(0);
        exposure_val->step(1);
        exposure_val->value(100);
        exposure_val->callback((Fl_Callback*)do_exposure_cb);
        exposure_val->align(FL_ALIGN_TOP);
      } // Fl_Slider* exposure_val
      { gain_val = new Fl_Slider(320, 40, 20, 130, "Gain");
        gain_val->type(4);
        gain_val->labelsize(11);
        gain_val->maximum(100);
        gain_val->step(1);
        gain_val->callback((Fl_Callback*)do_gain_cb);
        gain_val->align(FL_ALIGN_TOP);
      } // Fl_Slider* gain_val
      { brightness_val = new Fl_Slider(375, 40, 20, 130, "Bright");
        brightness_val->type(4);
        brightness_val->labelsize(11);
        brightness_val->maximum(100);
        brightness_val->step(1);
        brightness_val->callback((Fl_Callback*)do_brightness_cb);
        brightness_val->align(FL_ALIGN_TOP);
      } // Fl_Slider* brightness_val
      { exposure_auto_button = new Fl_Light_Button(255, 175, 40, 20, "Auto");
        exposure_auto_button->value(1);
        exposure_auto_button->labelsize(11);
        exposure_auto_button->callback((Fl_Callback*)do_auto_exposure_cb);
      } // Fl_Light_Button* exposure_auto_button
      { gain_auto_button = new Fl_Light_Button(310, 175, 40, 20, "Auto");
        gain_auto_button->value(1);
        gain_auto_button->labelsize(11);
        gain_auto_button->callback((Fl_Callback*)do_auto_gain_cb);
      } // Fl_Light_Button* gain_auto_button
      { brightness_auto_button = new Fl_Light_Button(365, 175, 40, 20, "Auto");
        brightness_auto_button->value(1);
        brightness_auto_button->labelsize(11);
        brightness_auto_button->callback((Fl_Callback*)do_auto_brightness_cb);
      } // Fl_Light_Button* brightness_auto_button
      { gamma_button = new Fl_Light_Button(190, 135, 55, 25, "Gamma");
        gamma_button->value(1);
        gamma_button->labelsize(11);
        gamma_button->callback((Fl_Callback*)do_gamma_cb);
      } // Fl_Light_Button* gamma_button
      o->end();
    } // Fl_Group* o
    video_window->end();
  } // Fl_Window* video_window
}
