#!/bin/bash

# PLASMA_HOME is required to build the PLASMA NDDL.jar
export PLASMA_HOME=`rospack find trex`/PLASMA/

# Build the debug version
jam exec_trex

# Build the optimized version
jam -sVARIANTS=OPTIMIZED exec_trex
