#!/bin/bash
#This file is needed, to force the use of bash, so devConfig can be sourced.

if [ `uname` = Darwin ]; then
  export DYLD_BIND_AT_LAUNCH=YES
fi

# Set up a build directory with suitable soft link & environment variable bindings
ln -s `rospack find trex_core` ~/trex_core_build
cd ~/trex_core_build
source ./TREX/devConfig
cd TREX

echo "Building nddl.jar with jam"
# Build the nddl jar file used to parse input files
jam  -q nddl.jar

if [ $? -ne 0 ] ; then
    echo "Jam of nddl.jar failed."
    exit 1
fi


# Build function takes:
# 1. library name
# 2. jam flags
# 3. return error code
function run_jam {

  echo "Running jam with command" $1 " and options" $2
  if [ `uname` = Darwin ]; then
    jam $2  -q $1.dylib
  else
    jam $2  -q $1.so
  fi
  if [ $? -ne 0 ] ; then
    echo "Jam of $1 failed."
    exit $3
  fi
}


if [ "$1" = "test" ] ; then
  if [ $? -ne 0 ] ; then
    echo "TREX test file creation failed."
    exit 1
  fi
  jam run-agent-module-tests
  if [ $? -ne 0 ] ; then
    echo "TREX tests failed."
    exit 1
  fi

else
  if [ "$ROS_TREX_DEBUG" = "1" ] ; then
      run_jam "libTREX_g" " " 1
  fi
  jam nddl-reader
  run_jam "libTREX_o" "-sVARIANTS=OPTIMIZED -sLIBRARIES=SHARED" 2
fi

cd `rospack find trex_core`

